


// import { useState, useEffect, useRef } from "react";
// import Head from "next/head";
// import { getApiResponse } from './api/response';
// import Link from "next/link";
// import { IoIosArrowBack } from "react-icons/io";
// import { MdAccountCircle } from 'react-icons/md';

// export default function Home({ Logout, user }) {
//   const [dropdown, setDropdown] = useState(false);
//   const [notification, setNotification] = useState(false); // State to track the notification
//   const [isStored, setIsStored] = useState(false); // To track if the item is successfully stored in localStorage

//   useEffect(() => {
//     // Request microphone (audio) access
//     const requestPermissions = async () => {
//       try {
//         // Requesting audio permission (microphone)
//         await navigator.mediaDevices.getUserMedia({ audio: true, sound: true });
//         console.log("Microphone and sound access granted.");
//       } catch (err) {
//         console.error("Microphone and sound access denied:", err);
//         // Optionally, show an alert or message to the user about the permission issue
//       }
//     };

//     requestPermissions();

//     // Check if there’s a notification stored in localStorage when the component mounts
//     const checkStorage = () => {
//       const storedNotification = localStorage.getItem("store");
//       if (storedNotification) {
//         setNotification(true);
//       }
//     };

//     checkStorage();
//   }, []);

//   const toggleDropdown = () => setDropdown(prev => !prev);

//   // Function to simulate storing an item in localStorage and triggering the notification
//   const handleReportClick = () => {
//     localStorage.removeItem("store"); // Remove notification from localStorage
//     setNotification(false); // Hide the notification dot
//   };

//   return (<><Head>
//     <title>Shakktii Interview Trainer</title>
//     <meta name="description" content="Generated by create next app" />
//     <meta name="viewport" content="width=device-width, initial-scale=1" />
//     <link rel="icon" href="/favicon.ico" />
//   </Head>
//     <div className="min-h-screen bg-gradient-to-b text-white px-4 bg-cover flex flex-col items-center justify-center" style={{ backgroundImage: "url('/bg.gif')" }}>
//       {/* Navigation Bar */}
//       <nav className="flex justify-between items-center py-4 px-6 bg-black bg-opacity-50 w-full">
//         <div className="text-white text-lg font-bold">Shaktti AI</div>
//         <ul className="flex space-x-6 text-sm">
//           <li className="hover:text-purple-400 cursor-pointer">Home</li>
//           <Link href={'/oldreport'}>
//             <li className="relative hover:text-purple-400 cursor-pointer" onClick={handleReportClick}>
//               Reports
//               {/* Show the notification red dot if true */}
//               {notification && (
//                 <span className="absolute top-0 right-0 bg-red-500 text-white text-xs rounded-full w-2.5 h-2.5"></span>
//               )}
//             </li>
//           </Link>
//           <div className="relative">
//             {/* User Dropdown */}
//             {user?.value && (
//               <div className="relative">
//                 <MdAccountCircle
//                   className="text-2xl md:text-3xl mx-2 cursor-pointer"
//                   onClick={toggleDropdown} // Toggle on click
//                 />
//                 {dropdown && (
//                   <div className="absolute right-0 shadow-xl top-10 rounded-md w-40 border-2 border-solid border-gray-300">
//                     <ul>
//                       {/* Profile Link */}
//                       <Link href={'/profile'}><li className="hover:text-blue-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100">
//                         Profile
//                       </li></Link>
//                       {/* Logout Link */}
//                       <li
//                         onClick={Logout}
//                         className="hover:text-red-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100"
//                       >
//                         Logout
//                       </li>
//                     </ul>
//                   </div>
//                 )}
//               </div>
//             )}

//             {/* Login button for guests */}
//             {!user?.value && (
//               <Link href="/login">
//                 <div className="ml-4">
//                   <button className="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-opacity-50 transition ease-in-out duration-200">
//                     Login
//                   </button>
//                 </div>
//               </Link>
//             )}
//           </div>
//         </ul>
//       </nav>

//       {/* Header Section */}
//       <div className="flex flex-col items-center text-center">
//         {/* Logo */}
//         <div className="w-20 h-20 mt-5 border-2 border-white rounded-full flex items-center justify-center">
//           <img src="/Logo.png" alt="Logo" className="w-16 h-16 object-contain" />
//         </div>

//         <h1 className="text-4xl font-bold mt-4 text-pink-400">Job</h1>
//         <h2 className="text-3xl font-bold text-pink-500">Interview</h2>

//         {/* Image Section */}
//         <div className="flex justify-center mt-4 mb-4">
//           <img
//             src="/home.png"
//             alt="Job Interview"
//             className="max-w-sm w-full h-auto object-contain"
//           />
//         </div>

//         {/* Description */}
//         <p className="text-center text-gray-300 max-w-lg mx-auto">
//           Landing your dream job starts with a great interview. We provide expert tips, real-world
//           insights, and proven strategies to help you impress employers and stand out from the
//           competition.
//         </p>

//         {/* List of Services */}
//         <ul className="mt-4 text-center space-y-2 text-gray-200">
//           <li>✅ <span className="text-pink-400">Interview Preparation</span> - Master common questions.</li>
//           <li>✅ <span className="text-pink-400">Resume & Cover Letter Tips</span> - Showcase your skills.</li>
//           <li>✅ <span className="text-pink-400">Career Coaching</span> - Get expert guidance.</li>
//         </ul>

//         {/* Call to Action Button */}
//         <div className="mt-6 flex justify-center pb-10">
//           <Link href={'/role'}>
//             <button className="bg-pink-500 text-white py-3 px-6 rounded-lg text-lg font-semibold hover:bg-pink-600">
//               GET STARTED
//             </button>
//           </Link>
//         </div>
//       </div>
//     </div>
//     </>
//   );
// }

// import { useState, useEffect, useRef } from "react";
// import Head from "next/head";
// import Link from "next/link";
// import { useRouter } from 'next/router'; // For programmatic navigation
// import { IoIosArrowBack } from "react-icons/io";
// import { MdAccountCircle } from 'react-icons/md';

// export default function Home({ Logout, user }) {
//   const [dropdown, setDropdown] = useState(false);
//   const [notification, setNotification] = useState(false); // State to track the notification
//   const [isStored, setIsStored] = useState(false); // To track if the item is successfully stored in localStorage
//   const [speechRecognizing, setSpeechRecognizing] = useState(false); // State to track speech recognition status
//   const router = useRouter(); // Next.js router to navigate to /role

//   const recognition = useRef(null); // Reference to the speech recognition instance

//   useEffect(() => {
//     // Initialize Speech Recognition API
//     const initSpeechRecognition = () => {
//       if (window.SpeechRecognition || window.webkitSpeechRecognition) {
//         recognition.current = new (window.SpeechRecognition || window.webkitSpeechRecognition)();
//         recognition.current.lang = "en-US";
//         recognition.current.continuous = false;
//         recognition.current.interimResults = false;

//         recognition.current.onstart = () => {
//           console.log("Speech recognition started.");
//           setSpeechRecognizing(true);
//         };

//         recognition.current.onend = () => {
//           console.log("Speech recognition ended.");
//           setSpeechRecognizing(false);
//         };

//         recognition.current.onresult = (event) => {
//           const transcript = event.results[0][0].transcript.toLowerCase();
//           console.log("Transcript: ", transcript);

//           if (transcript.includes("i am ready")) {
//             router.push("/role"); // Redirect to /role when "I am ready" is spoken
//           }
//         };
//       } else {
//         console.error("Speech recognition is not supported in this browser.");
//       }
//     };

//     initSpeechRecognition();

//     // Check if there’s a notification stored in localStorage when the component mounts
//     const checkStorage = () => {
//       const storedNotification = localStorage.getItem("store");
//       if (storedNotification) {
//         setNotification(true);
//       }
//     };

//     checkStorage();
//   }, [router]);

//   const toggleDropdown = () => setDropdown(prev => !prev);

//   // Function to simulate storing an item in localStorage and triggering the notification
//   const handleReportClick = () => {
//     localStorage.removeItem("store"); // Remove notification from localStorage
//     setNotification(false); // Hide the notification dot
//   };

//   // Start the speech recognition when the component mounts or when the user clicks a button
//   const startRecognition = () => {
//     if (recognition.current) {
//       recognition.current.start(); // Start listening to the user's speech
//     }
//   };

//   return (
//     <>
//       <Head>
//         <title>Shakktii Interview Trainer</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <div className="min-h-screen bg-gradient-to-b text-white px-4 bg-cover flex flex-col items-center justify-center" style={{ backgroundImage: "url('/bg.gif')" }}>
//         {/* Navigation Bar */}
//         <nav className="flex justify-between items-center py-4 px-6 bg-black bg-opacity-50 w-full">
//           <div className="text-white text-lg font-bold">Shaktti AI</div>
//           <ul className="flex space-x-6 text-sm">
//             <li className="hover:text-purple-400 cursor-pointer">Home</li>
//             <Link href={'/oldreport'}>
//               <li className="relative hover:text-purple-400 cursor-pointer" onClick={handleReportClick}>
//                 Reports
//                 {/* Show the notification red dot if true */}
//                 {notification && (
//                   <span className="absolute top-0 right-0 bg-red-500 text-white text-xs rounded-full w-2.5 h-2.5"></span>
//                 )}
//               </li>
//             </Link>
//             <div className="relative">
//               {/* User Dropdown */}
//               {user?.value && (
//                 <div className="relative">
//                   <MdAccountCircle
//                     className="text-2xl md:text-3xl mx-2 cursor-pointer"
//                     onClick={toggleDropdown} // Toggle on click
//                   />
//                   {dropdown && (
//                     <div className="absolute right-0 shadow-xl top-10 rounded-md w-40 border-2 border-solid border-gray-300">
//                       <ul>
//                         {/* Profile Link */}
//                         <Link href={'/profile'}><li className="hover:text-blue-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100">
//                           Profile
//                         </li></Link>
//                         {/* Logout Link */}
//                         <li
//                           onClick={Logout}
//                           className="hover:text-red-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100"
//                         >
//                           Logout
//                         </li>
//                       </ul>
//                     </div>
//                   )}
//                 </div>
//               )}

//               {/* Login button for guests */}
//               {!user?.value && (
//                 <Link href="/login">
//                   <div className="ml-4">
//                     <button className="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-opacity-50 transition ease-in-out duration-200">
//                       Login
//                     </button>
//                   </div>
//                 </Link>
//               )}
//             </div>
//           </ul>
//         </nav>

//         {/* Header Section */}
//         <div className="flex flex-col items-center text-center">
//           {/* Logo */}
//           <div className="w-20 h-20 mt-5 border-2 border-white rounded-full flex items-center justify-center">
//             <img src="/Logo.png" alt="Logo" className="w-16 h-16 object-contain" />
//           </div>

//           <h1 className="text-4xl font-bold mt-4 text-pink-400">Job</h1>
//           <h2 className="text-3xl font-bold text-pink-500">Interview</h2>

//           {/* Image Section */}
//           <div className="flex justify-center mt-4 mb-4">
//             <img
//               src="/home.png"
//               alt="Job Interview"
//               className="max-w-sm w-full h-auto object-contain"
//             />
//           </div>

//           {/* Description */}
//           <p className="text-center text-gray-300 max-w-lg mx-auto">
//             Landing your dream job starts with a great interview. We provide expert tips, real-world
//             insights, and proven strategies to help you impress employers and stand out from the
//             competition.
//           </p>

//           {/* List of Services */}
//           <ul className="mt-4 text-center space-y-2 text-gray-200">
//             <li>✅ <span className="text-pink-400">Interview Preparation</span> - Master common questions.</li>
//             <li>✅ <span className="text-pink-400">Resume & Cover Letter Tips</span> - Showcase your skills.</li>
//             <li>✅ <span className="text-pink-400">Career Coaching</span> - Get expert guidance.</li>
//           </ul>

//           {/* Call to Action Button */}
//           <div className="mt-6 flex justify-center pb-10">
//             {/* Replacing the button with speech recognition trigger */}
//             {!speechRecognizing && (
//               <button
//                 onClick={startRecognition}
//                 className="bg-pink-500 text-white py-3 px-6 rounded-lg text-lg font-semibold hover:bg-pink-600"
//               >
//                 Speak "I am ready" to Get Started
//               </button>
//             )}
//           </div>
//         </div>
//       </div>
//     </>
//   );
// }

// import { useState, useEffect, useRef } from "react";
// import Head from "next/head";
// import Link from "next/link";
// import { useRouter } from 'next/router'; // For programmatic navigation
// import { IoIosArrowBack } from "react-icons/io";
// import { MdAccountCircle } from 'react-icons/md';

// export default function Home({ Logout, user }) {
//   const [dropdown, setDropdown] = useState(false);
//   const [notification, setNotification] = useState(false); // State to track the notification
//   const [isStored, setIsStored] = useState(false); // To track if the item is successfully stored in localStorage
//   const [speechRecognizing, setSpeechRecognizing] = useState(false); // State to track speech recognition status
//   const router = useRouter(); // Next.js router to navigate to /role

//   const recognition = useRef(null); // Reference to the speech recognition instance

//   useEffect(() => {
//     // Initialize Speech Recognition API
//     const initSpeechRecognition = () => {
//       if (window.SpeechRecognition || window.webkitSpeechRecognition) {
//         recognition.current = new (window.SpeechRecognition || window.webkitSpeechRecognition)();
//         recognition.current.lang = "en-US";
//         recognition.current.continuous = true; // Continuous recognition
//         recognition.current.interimResults = false;

//         recognition.current.onstart = () => {
//           console.log("Speech recognition started.");
//           setSpeechRecognizing(true);
//         };

//         recognition.current.onend = () => {
//           console.log("Speech recognition ended.");
//           setSpeechRecognizing(false);
//         };

//         recognition.current.onresult = (event) => {
//           const transcript = event.results[0][0].transcript.toLowerCase();
//           console.log("Transcript: ", transcript);

//           if (transcript.includes("i am ready")) {
//             router.push("/role"); // Redirect to /role when "I am ready" is spoken
//           }
//         };

//         // Start listening when the page loads
//         recognition.current.start();
//       } else {
//         console.error("Speech recognition is not supported in this browser.");
//       }
//     };

//     initSpeechRecognition();

//     // Check if there’s a notification stored in localStorage when the component mounts
//     const checkStorage = () => {
//       const storedNotification = localStorage.getItem("store");
//       if (storedNotification) {
//         setNotification(true);
//       }
//     };

//     checkStorage();
//   }, [router]);

//   const toggleDropdown = () => setDropdown(prev => !prev);

//   // Function to simulate storing an item in localStorage and triggering the notification
//   const handleReportClick = () => {
//     localStorage.removeItem("store"); // Remove notification from localStorage
//     setNotification(false); // Hide the notification dot
//   };

//   return (
//     <>
//       <Head>
//         <title>Shakktii Interview Trainer</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <div className="min-h-screen bg-gradient-to-b text-white px-4 bg-cover flex flex-col items-center justify-center" style={{ backgroundImage: "url('/bg.gif')" }}>
//         {/* Navigation Bar */}
//         <nav className="flex justify-between items-center py-4 px-6 bg-black bg-opacity-50 w-full">
//           <div className="text-white text-lg font-bold">Shaktti AI</div>
//           <ul className="flex space-x-6 text-sm">
//             <li className="hover:text-purple-400 cursor-pointer">Home</li>
//             <Link href={'/oldreport'}>
//               <li className="relative hover:text-purple-400 cursor-pointer" onClick={handleReportClick}>
//                 Reports
//                 {/* Show the notification red dot if true */}
//                 {notification && (
//                   <span className="absolute top-0 right-0 bg-red-500 text-white text-xs rounded-full w-2.5 h-2.5"></span>
//                 )}
//               </li>
//             </Link>
//             <div className="relative">
//               {/* User Dropdown */}
//               {user?.value && (
//                 <div className="relative">
//                   <MdAccountCircle
//                     className="text-2xl md:text-3xl mx-2 cursor-pointer"
//                     onClick={toggleDropdown} // Toggle on click
//                   />
//                   {dropdown && (
//                     <div className="absolute right-0 shadow-xl top-10 rounded-md w-40 border-2 border-solid border-gray-300">
//                       <ul>
//                         {/* Profile Link */}
//                         <Link href={'/profile'}><li className="hover:text-blue-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100">
//                           Profile
//                         </li></Link>
//                         {/* Logout Link */}
//                         <li
//                           onClick={Logout}
//                           className="hover:text-red-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100"
//                         >
//                           Logout
//                         </li>
//                       </ul>
//                     </div>
//                   )}
//                 </div>
//               )}

//               {/* Login button for guests */}
//               {!user?.value && (
//                 <Link href="/login">
//                   <div className="ml-4">
//                     <button className="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-opacity-50 transition ease-in-out duration-200">
//                       Login
//                     </button>
//                   </div>
//                 </Link>
//               )}
//             </div>
//           </ul>
//         </nav>

//         {/* Header Section */}
//         <div className="flex flex-col items-center text-center">
//           {/* Logo */}
//           <div className="w-20 h-20 mt-5 border-2 border-white rounded-full flex items-center justify-center">
//             <img src="/Logo.png" alt="Logo" className="w-16 h-16 object-contain" />
//           </div>

//           <h1 className="text-4xl font-bold mt-4 text-pink-400">Job</h1>
//           <h2 className="text-3xl font-bold text-pink-500">Interview</h2>

//           {/* Image Section */}
//           <div className="flex justify-center mt-4 mb-4">
//             <img
//               src="/home.png"
//               alt="Job Interview"
//               className="max-w-sm w-full h-auto object-contain"
//             />
//           </div>

//           {/* Description */}
//           <p className="text-center text-gray-300 max-w-lg mx-auto">
//             Landing your dream job starts with a great interview. We provide expert tips, real-world
//             insights, and proven strategies to help you impress employers and stand out from the
//             competition.
//           </p>

//           {/* List of Services */}
//           <ul className="mt-4 text-center space-y-2 text-gray-200">
//             <li>✅ <span className="text-pink-400">Interview Preparation</span> - Master common questions.</li>
//             <li>✅ <span className="text-pink-400">Resume & Cover Letter Tips</span> - Showcase your skills.</li>
//             <li>✅ <span className="text-pink-400">Career Coaching</span> - Get expert guidance.</li>
//           </ul>

//           {/* Informational text about speech recognition */}
//           <div className="mt-6 flex justify-center pb-10">
//             <p className="text-lg font-semibold text-gray-200">
//               Please speak the phrase <span className="text-pink-500">"I am ready"</span> to proceed.
//             </p>
//           </div>
//         </div>
//       </div>
//     </>
//   );
// }


// import { useState, useEffect, useRef } from "react";
// import Link from "next/link";
// import Head from "next/head";
// import { IoIosArrowBack } from "react-icons/io";
// import { MdAccountCircle } from 'react-icons/md';
// import { useRouter } from 'next/router'; // For programmatic navigation

// export default function Home({ Logout, user }) {
//   const [dropdown, setDropdown] = useState(false);
//   const [notification, setNotification] = useState(false); // State to track the notification
//   const router = useRouter(); // Next.js router to navigate to /role

//   const recognition = useRef(null); // Reference to the speech recognition instance

//   useEffect(() => {
//     // Initialize Speech Recognition API
//     const initSpeechRecognition = () => {
//       if (window.SpeechRecognition || window.webkitSpeechRecognition) {
//         recognition.current = new (window.SpeechRecognition || window.webkitSpeechRecognition)();
//         recognition.current.lang = "en-US";
//         recognition.current.continuous = true; // Continuous recognition
//         recognition.current.interimResults = false;

//         recognition.current.onstart = () => {
//           console.log("Speech recognition started.");
//         };

//         recognition.current.onend = () => {
//           console.log("Speech recognition ended.");
//           if(!recognition.current.onstart){

//         }
//           // You can try to restart recognition only if it's completely ended.
//           // No need to call start() here if it's already restarted before
//         };

//         recognition.current.onresult = (event) => {
//           const transcript = event.results[0][0].transcript.toLowerCase();
//           console.log("Transcript: ", transcript);

//           if (transcript.includes("i am ready")) {
//             router.push("/role"); // Redirect to /role when "I am ready" is spoken
//           }
//         };

//         // Start listening when the page loads
//         recognition.current.start();
//       } else {
//         console.error("Speech recognition is not supported in this browser.");
//       }
//     };

//     initSpeechRecognition();

//     // Check if there’s a notification stored in localStorage when the component mounts
//     const checkStorage = () => {
//       const storedNotification = localStorage.getItem("store");
//       if (storedNotification) {
//         setNotification(true);
//       }
//     };

//     checkStorage();
//   }, [router]);

//   const toggleDropdown = () => setDropdown(prev => !prev);

//   // Function to simulate storing an item in localStorage and triggering the notification
//   const handleReportClick = () => {
//     localStorage.removeItem("store"); // Remove notification from localStorage
//     setNotification(false); // Hide the notification dot
//   };

//   return (
//     <>
//       <Head>
//         <title>Shakktii Interview Trainer</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <div className="min-h-screen bg-gradient-to-b text-white px-4 bg-cover flex flex-col items-center justify-center" style={{ backgroundImage: "url('/bg.gif')" }}>
//         {/* Navigation Bar */}
//         <nav className="flex justify-between items-center py-4 px-6 bg-black bg-opacity-50 w-full">
//           <div className="text-white text-lg font-bold">Shaktti AI</div>
//           <ul className="flex space-x-6 text-sm">
//             <li className="hover:text-purple-400 cursor-pointer">Home</li>
//             <Link href={'/oldreport'}>
//               <li className="relative hover:text-purple-400 cursor-pointer" onClick={handleReportClick}>
//                 Reports
//                 {/* Show the notification red dot if true */}
//                 {notification && (
//                   <span className="absolute top-0 right-0 bg-red-500 text-white text-xs rounded-full w-2.5 h-2.5"></span>
//                 )}
//               </li>
//             </Link>
//             <div className="relative">
//               {/* User Dropdown */}
//               {user?.value && (
//                 <div className="relative">
//                   <MdAccountCircle
//                     className="text-2xl md:text-3xl mx-2 cursor-pointer"
//                     onClick={toggleDropdown} // Toggle on click
//                   />
//                   {dropdown && (
//                     <div className="absolute right-0 shadow-xl top-10 rounded-md w-40 border-2 border-solid border-gray-300">
//                       <ul>
//                         {/* Profile Link */}
//                         <Link href={'/profile'}><li className="hover:text-blue-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100">
//                           Profile
//                         </li></Link>
//                         {/* Logout Link */}
//                         <li
//                           onClick={Logout}
//                           className="hover:text-red-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100"
//                         >
//                           Logout
//                         </li>
//                       </ul>
//                     </div>
//                   )}
//                 </div>
//               )}

//               {/* Login button for guests */}
//               {!user?.value && (
//                 <Link href="/login">
//                   <div className="ml-4">
//                     <button className="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-opacity-50 transition ease-in-out duration-200">
//                       Login
//                     </button>
//                   </div>
//                 </Link>
//               )}
//             </div>
//           </ul>
//         </nav>

//         {/* Header Section */}
//         <div className="flex flex-col items-center text-center">
//           {/* Logo */}
//           <div className="w-20 h-20 mt-5 border-2 border-white rounded-full flex items-center justify-center">
//             <img src="/Logo.png" alt="Logo" className="w-16 h-16 object-contain" />
//           </div>

//           <h1 className="text-4xl font-bold mt-4 text-pink-400">Job</h1>
//           <h2 className="text-3xl font-bold text-pink-500">Interview</h2>

//           {/* Image Section */}
//           <div className="flex justify-center mt-4 mb-4">
//             <img
//               src="/home.png"
//               alt="Job Interview"
//               className="max-w-sm w-full h-auto object-contain"
//             />
//           </div>

//           {/* Description */}
//           <p className="text-center text-gray-300 max-w-lg mx-auto">
//             Landing your dream job starts with a great interview. We provide expert tips, real-world
//             insights, and proven strategies to help you impress employers and stand out from the
//             competition.
//           </p>

//           {/* List of Services */}
//           <ul className="mt-4 text-center space-y-2 text-gray-200">
//             <li>✅ <span className="text-pink-400">Interview Preparation</span> - Master common questions.</li>
//             <li>✅ <span className="text-pink-400">Resume & Cover Letter Tips</span> - Showcase your skills.</li>
//             <li>✅ <span className="text-pink-400">Career Coaching</span> - Get expert guidance.</li>
//           </ul>

//           {/* Informational text about speech recognition */}
//           <div className="mt-6 flex justify-center pb-10">
//             <p className="text-lg font-semibold text-gray-200">
//               Please speak the phrase <span className="text-pink-500">"I am ready"</span> to proceed.
//             </p>
//           </div>
//         </div>
//       </div>
//     </>
//   );
// }



// import { useState, useEffect, useRef } from "react";
// import Link from "next/link";
// import Head from "next/head";
// import { IoIosArrowBack } from "react-icons/io";
// import { MdAccountCircle } from 'react-icons/md';
// import { useRouter } from 'next/router'; // For programmatic navigation



// export default function Home({ Logout, user }) {
//   const [dropdown, setDropdown] = useState(false);
//   const [notification, setNotification] = useState(false); // State to track the notification
//   const router = useRouter(); // Next.js router to navigate to /role
//   const recognition = useRef(null); // Reference to the speech recognition instance
//   const [isRecognizing, setIsRecognizing] = useState(false); // To track whether recognition is ongoing

//   useEffect(() => {
//     // Initialize Speech Recognition API
//     const initSpeechRecognition = () => {
//       if (window.SpeechRecognition || window.webkitSpeechRecognition) {
//         recognition.current = new (window.SpeechRecognition || window.webkitSpeechRecognition)();
//         recognition.current.lang = "en-US";
//         recognition.current.continuous = true; // Continuous recognition
//         recognition.current.interimResults = false;

//         recognition.current.onstart = () => {
//           console.log("Speech recognition started.");
//           setIsRecognizing(true); // Set the recognizing flag to true
//         };

//         recognition.current.onend = () => {
//           console.log("Speech recognition ended.");
//           setIsRecognizing(false); // Set the recognizing flag to false

//           // Restart recognition only if it's fully ended and not already recognizing
//           if (recognition.current && !isRecognizing && recognition.current.state === "inactive") {
//             console.log("Speech recognition restarted."); // Debug log
//             recognition.current.start(); // Restart recognition
//           }
//         };

//         recognition.current.onresult = (event) => {
//           const transcript = event.results[0][0].transcript.toLowerCase();
//           console.log("Transcript: ", transcript);

//           // If the user says "I am ready", navigate to /role
//           if (transcript.includes("i am ready")) {
//             router.push("/role"); // Redirect to /role when "I am ready" is spoken
//           }
//         };

//         // Start listening when the page loads if it's not already started
//         if (recognition.current && !isRecognizing) {
//           recognition.current.start();
//         }
//       } else {
//         console.error("Speech recognition is not supported in this browser.");
//       }
//     };

//     initSpeechRecognition();

//     // Check if there’s a notification stored in localStorage when the component mounts
//     const checkStorage = () => {
//       const storedNotification = localStorage.getItem("store");
//       if (storedNotification) {
//         setNotification(true);
//       }
//     };

//     checkStorage();
//   }, [router, isRecognizing]);

//   const toggleDropdown = () => setDropdown(prev => !prev);

//   // Function to simulate storing an item in localStorage and triggering the notification
//   const handleReportClick = () => {
//     localStorage.removeItem("store"); // Remove notification from localStorage
//     setNotification(false); // Hide the notification dot
//   };

//   return (
//     <>
//       <Head>
//         <title>Shakktii Interview Trainer</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <div className="min-h-screen bg-gradient-to-b text-white px-4 bg-cover flex flex-col items-center justify-center" style={{ backgroundImage: "url('/bg.gif')" }}>
//         {/* Navigation Bar */}
//         <nav className="flex justify-between items-center py-4 px-6 bg-black bg-opacity-50 w-full">
//           <div className="text-white text-lg font-bold">Shaktti AI</div>
//           <ul className="flex space-x-6 text-sm">
//             <li className="hover:text-purple-400 cursor-pointer">Home</li>
//             <Link href={'/oldreport'}>
//               <li className="relative hover:text-purple-400 cursor-pointer" onClick={handleReportClick}>
//                 Reports
//                 {/* Show the notification red dot if true */}
//                 {notification && (
//                   <span className="absolute top-0 right-0 bg-red-500 text-white text-xs rounded-full w-2.5 h-2.5"></span>
//                 )}
//               </li>
//             </Link>
//             <div className="relative">
//               {/* User Dropdown */}
//               {user?.value && (
//                 <div className="relative">
//                   <MdAccountCircle
//                     className="text-2xl md:text-3xl mx-2 cursor-pointer"
//                     onClick={toggleDropdown} // Toggle on click
//                   />
//                   {dropdown && (
//                     <div className="absolute right-0 shadow-xl top-10 rounded-md w-40 border-2 border-solid border-gray-300">
//                       <ul>
//                         {/* Profile Link */}
//                         <Link href={'/profile'}><li className="hover:text-blue-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100">
//                           Profile
//                         </li></Link>
//                         {/* Logout Link */}
//                         <li
//                           onClick={Logout}
//                           className="hover:text-red-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100"
//                         >
//                           Logout
//                         </li>
//                       </ul>
//                     </div>
//                   )}
//                 </div>
//               )}

//               {/* Login button for guests */}
//               {!user?.value && (
//                 <Link href="/login">
//                   <div className="ml-4">
//                     <button className="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-opacity-50 transition ease-in-out duration-200">
//                       Login
//                     </button>
//                   </div>
//                 </Link>
//               )}
//             </div>
//           </ul>
//         </nav>

//         {/* Header Section */}
//         <div className="flex flex-col items-center text-center">
//           {/* Logo */}
//           <div className="w-20 h-20 mt-5 border-2 border-white rounded-full flex items-center justify-center">
//             <img src="/Logo.png" alt="Logo" className="w-16 h-16 object-contain" />
//           </div>

//           <h1 className="text-4xl font-bold mt-4 text-pink-400">Job</h1>
//           <h2 className="text-3xl font-bold text-pink-500">Interview</h2>

//           {/* Image Section */}
//           <div className="flex justify-center mt-4 mb-4">
//             <img
//               src="/home.png"
//               alt="Job Interview"
//               className="max-w-sm w-full h-auto object-contain"
//             />
//           </div>

//           {/* Description */}
//           <p className="text-center text-gray-300 max-w-lg mx-auto">
//             Landing your dream job starts with a great interview. We provide expert tips, real-world
//             insights, and proven strategies to help you impress employers and stand out from the
//             competition.
//           </p>

//           {/* List of Services */}
//           <ul className="mt-4 text-center space-y-2 text-gray-200">
//             <li>✅ <span className="text-pink-400">Interview Preparation</span> - Master common questions.</li>
//             <li>✅ <span className="text-pink-400">Resume & Cover Letter Tips</span> - Showcase your skills.</li>
//             <li>✅ <span className="text-pink-400">Career Coaching</span> - Get expert guidance.</li>
//           </ul>

//           {/* Informational text about speech recognition */}
//           <div className="mt-6 flex justify-center pb-10">
//             <p className="text-lg font-semibold text-gray-200">
//               Please speak the phrase <span className="text-pink-500">"I am ready"</span> to proceed.
//             </p>
//           </div>
//           Speak OR Click On Get Started
//           <div className="mt-6 flex justify-center pb-10">
//             <Link href={'/role'}>
//               <button className="bg-pink-500 text-white py-3 px-6 rounded-lg text-lg font-semibold hover:bg-pink-600">
//                 GET STARTED
//               </button>
//             </Link>
//           </div>
//         </div>
//       </div>
//     </>
//   );
// }



// //perfect
// import { useState, useEffect, useRef } from "react";
// import Link from "next/link";
// import Head from "next/head";
// import { IoIosArrowBack } from "react-icons/io";
// import { MdAccountCircle } from 'react-icons/md';
// import { useRouter } from 'next/router'; // For programmatic navigation



// export default function Home({ Logout, user }) {
//   const [dropdown, setDropdown] = useState(false);
//   const [notification, setNotification] = useState(false); // State to track the notification
//   const router = useRouter(); // Next.js router to navigate to /role
//   const recognition = useRef(null); // Reference to the speech recognition instance
//   const [isRecognizing, setIsRecognizing] = useState(false); // To track whether recognition is ongoing
// const[userr, setUserr] = useState(null);

//   const speak = (text) => {
//     const utterance = new SpeechSynthesisUtterance(text);
//     utterance.lang = 'en-US'; // Set language to English


//     window.speechSynthesis.speak(utterance);
//   };



// // console.log("this is User",user);


// useEffect(() => {
//   const userFromStorage = JSON.parse(localStorage.getItem('user'));

//   // console.log(userFromStorage);
//   setUserr(userFromStorage);

//   // No need to speak until the user is set
//   if (userFromStorage) {
//     // Speak the instructions once user data is loaded
//     const firstName = userFromStorage?.fullName?.split(' ')[0];
//     speak(`Hey ${firstName}, welcome back! Just say 'I'm ready' when you're all set!`);
//   }
// }, []); // Only runs once when the component is mounted


//   useEffect(() => {
//     // Initialize Speech Recognition API

//     const initSpeechRecognition = () => {
//       if (window.SpeechRecognition || window.webkitSpeechRecognition) {
//         recognition.current = new (window.SpeechRecognition || window.webkitSpeechRecognition)();
//         recognition.current.lang = "en-US";
//         recognition.current.continuous = true; // Continuous recognition
//         recognition.current.interimResults = false;

//         recognition.current.onstart = () => {
//           console.log("Speech recognition started.");
//           setIsRecognizing(true); // Set the recognizing flag to true
//         };

//         recognition.current.onend = () => {
//           console.log("Speech recognition ended.");
//           setIsRecognizing(false); // Set the recognizing flag to false

//           // Restart recognition only if it's fully ended and not already recognizing
//           if (recognition.current && !isRecognizing && recognition.current.state === "inactive") {
//             console.log("Speech recognition restarted."); // Debug log
//             recognition.current.start(); // Restart recognition
//           }
//         };

//         recognition.current.onresult = (event) => {
//           const transcript = event.results[0][0].transcript.toLowerCase();
//           console.log("Transcript: ", transcript);

//           // If the user says "I am ready", navigate to /role
//           if (transcript.includes("i am ready")) {
//             router.push("/role"); // Redirect to /role when "I am ready" is spoken
//           }
//         };

//         // Start listening when the page loads if it's not already started
//         if (recognition.current && !isRecognizing) {
//           recognition.current.start();
//         }
//       } else {
//         console.error("Speech recognition is not supported in this browser.");
//       }
//     };

//     initSpeechRecognition();

//     // Check if there’s a notification stored in localStorage when the component mounts
//     const checkStorage = () => {
//       const storedNotification = localStorage.getItem("store");
//       if (storedNotification) {
//         setNotification(true);
//       }
//     };

//     checkStorage();
//   }, [router, isRecognizing]);

//   const toggleDropdown = () => setDropdown(prev => !prev);

//   // Function to simulate storing an item in localStorage and triggering the notification
//   const handleReportClick = () => {
//     localStorage.removeItem("store"); // Remove notification from localStorage
//     setNotification(false); // Hide the notification dot
//   };

//   return (
//     <>
//       <Head>
//         <title>Shakktii Interview Trainer</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <div className="min-h-screen bg-gradient-to-b text-white px-4 bg-cover flex flex-col items-center justify-center" style={{ backgroundImage: "url('/bg.gif')" }}>
//         {/* Navigation Bar */}
//         <nav className="flex justify-between items-center py-4 px-6 bg-black bg-opacity-50 w-full">
//           <div className="text-white text-lg font-bold">Shaktti AI</div>
//           <ul className="flex space-x-6 text-sm">
//             <li className="hover:text-purple-400 cursor-pointer">Home</li>
//             <Link href={'/oldreport'}>
//               <li className="relative hover:text-purple-400 cursor-pointer" onClick={handleReportClick}>
//                 Reports
//                 {/* Show the notification red dot if true */}
//                 {notification && (
//                   <span className="absolute top-0 right-0 bg-red-500 text-white text-xs rounded-full w-2.5 h-2.5"></span>
//                 )}
//               </li>
//             </Link>
//             <div className="relative">
//               {/* User Dropdown */}
//               {user?.value && (
//                 <div className="relative">
//                   <MdAccountCircle
//                     className="text-2xl md:text-3xl mx-2 cursor-pointer"
//                     onClick={toggleDropdown} // Toggle on click
//                   />
//                   {dropdown && (
//                     <div className="absolute right-0 shadow-xl top-10 rounded-md w-40 border-2 border-solid border-gray-300">
//                       <ul>
//                         {/* Profile Link */}
//                         <Link href={'/profile'}><li className="hover:text-blue-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100">
//                           Profile
//                         </li></Link>
//                         {/* Logout Link */}
//                         <li
//                           onClick={Logout}
//                           className="hover:text-red-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100"
//                         >
//                           Logout
//                         </li>
//                       </ul>
//                     </div>
//                   )}
//                 </div>
//               )}

//               {/* Login button for guests */}
//               {!user?.value && (
//                 <Link href="/login">
//                   <div className="ml-4">
//                     <button className="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-opacity-50 transition ease-in-out duration-200">
//                       Login
//                     </button>
//                   </div>
//                 </Link>
//               )}
//             </div>
//           </ul>
//         </nav>

//         {/* Header Section */}
//         <div className="flex flex-col items-center text-center">
//           {/* Logo */}
//           <div className="w-20 h-20 mt-5 border-2 border-white rounded-full flex items-center justify-center">
//             <img src="/Logo.png" alt="Logo" className="w-16 h-16 object-contain" />
//           </div>

//           <h1 className="text-4xl font-bold mt-4 text-pink-400">Job</h1>
//           <h2 className="text-3xl font-bold text-pink-500">Interview</h2>

//           {/* Image Section */}
//           <div className="flex justify-center mt-4 mb-4">
//             <img
//               src="/home.png"
//               alt="Job Interview"
//               className="max-w-sm w-full h-auto object-contain"
//             />
//           </div>

//           {/* Description */}
//           <p className="text-center text-gray-300 max-w-lg mx-auto">
//             Landing your dream job starts with a great interview. We provide expert tips, real-world
//             insights, and proven strategies to help you impress employers and stand out from the
//             competition.
//           </p>

//           {/* List of Services */}
//           <ul className="mt-4 text-center space-y-2 text-gray-200">
//             <li>✅ <span className="text-pink-400">Interview Preparation</span> - Master common questions.</li>
//             <li>✅ <span className="text-pink-400">Resume & Cover Letter Tips</span> - Showcase your skills.</li>
//             <li>✅ <span className="text-pink-400">Career Coaching</span> - Get expert guidance.</li>
//           </ul>

//           {/* Informational text about speech recognition */}
//           <div className="mt-6 flex justify-center pb-10">
//             <p className="text-lg font-semibold text-gray-200">
//               Please speak the phrase <span className="text-pink-500">"I am ready"</span> to proceed.
//             </p>
//           </div>
//           Speak OR Click On Get Started
//           <div className="mt-6 flex justify-center pb-10">
//             <Link href={'/role'}>
//               <button className="bg-pink-500 text-white py-3 px-6 rounded-lg text-lg font-semibold hover:bg-pink-600">
//                 GET STARTED
//               </button>
//             </Link>
//           </div>

//         </div>
//       </div>
//     </>
//   );
// }



// import { useState, useEffect, useRef } from "react";
// import OwlModel from '../components/OwlModel'
// import Link from "next/link";
// import Head from "next/head";
// import { IoIosArrowBack } from "react-icons/io";
// import { MdAccountCircle } from 'react-icons/md';
// import { useRouter } from 'next/router'; // For programmatic navigation

// export default function Home({ Logout, user }) {
//   const [dropdown, setDropdown] = useState(false);
//   const [notification, setNotification] = useState(false); // State to track the notification
//   const router = useRouter(); // Next.js router to navigate to /role
//   const recognition = useRef(null); // Reference to the speech recognition instance
//   const [isRecognizing, setIsRecognizing] = useState(false); // To track whether recognition is ongoing

//   const speak = (text) => {
//     const utterance = new SpeechSynthesisUtterance(text);
//     utterance.lang = 'en-US'; // Set language to English
//     window.speechSynthesis.speak(utterance);
//   };

//   useEffect(() => {
//     // Delay speech synthesis for 1 second after page load
//     const timeoutId = setTimeout(() => {
//       // Check if the device is iOS and adjust the speech message accordingly
//       if (/iPhone|iPad|iPod/i.test(navigator.userAgent)) {
//         speak('Hi, I am Shakti, your interview trainer! Tap the screen to continue.');
//       } else {
//         speak('Hi, I am Shakti, your interview trainer! When you are ready, then speak the phrase "I am ready."');
//       }
//     }, 5000); // Delay by 1 second after page load

//     return () => clearTimeout(timeoutId); // Cleanup timeout on component unmount
//   }, []);

//   useEffect(() => {
//     // Initialize Speech Recognition API
//     const initSpeechRecognition = () => {
//       if (window.SpeechRecognition || window.webkitSpeechRecognition) {
//         recognition.current = new (window.SpeechRecognition || window.webkitSpeechRecognition)();
//         recognition.current.lang = "en-US";
//         recognition.current.continuous = true; // Continuous recognition
//         recognition.current.interimResults = false;

//         recognition.current.onstart = () => {
//           console.log("Speech recognition started.");
//           setIsRecognizing(true); // Set the recognizing flag to true
//         };

//         recognition.current.onend = () => {
//           console.log("Speech recognition ended.");
//           setIsRecognizing(false); // Set the recognizing flag to false

//           // Restart recognition only if it's fully ended and not already recognizing
//           if (recognition.current && !isRecognizing && recognition.current.state === "inactive") {
//             console.log("Speech recognition restarted."); // Debug log
//             recognition.current.start(); // Restart recognition
//           }
//         };

//         recognition.current.onresult = (event) => {
//           const transcript = event.results[0][0].transcript.toLowerCase();
//           console.log("Transcript: ", transcript);

//           // If the user says "I am ready", navigate to /role
//           if (transcript.includes("i am ready")) {
//             router.push("/role"); // Redirect to /role when "I am ready" is spoken
//           }
//         };

//         // Start listening when the page loads if it's not already started
//         if (recognition.current && !isRecognizing) {
//           recognition.current.start();
//         }
//       } else {
//         console.error("Speech recognition is not supported in this browser.");
//       }
//     };

//     initSpeechRecognition();

//     // Check if there’s a notification stored in localStorage when the component mounts
//     const checkStorage = () => {
//       const storedNotification = localStorage.getItem("store");
//       if (storedNotification) {
//         setNotification(true);
//       }
//     };

//     checkStorage();
//   }, [router, isRecognizing]);

//   const toggleDropdown = () => setDropdown(prev => !prev);

//   // Function to simulate storing an item in localStorage and triggering the notification
//   const handleReportClick = () => {
//     localStorage.removeItem("store"); // Remove notification from localStorage
//     setNotification(false); // Hide the notification dot
//   };

//   return (
//     <>
//       <Head>
//         <title>Shakktii Interview Trainer</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <div className="min-h-screen bg-gradient-to-b text-white px-4 bg-cover flex flex-col items-center justify-center" style={{ backgroundImage: "url('/bg.gif')" }}>
//         {/* Navigation Bar */}
//         <nav className="flex justify-between items-center py-4 px-6 bg-black bg-opacity-50 w-full">
//           <div className="text-white text-lg font-bold">Shaktti AI</div>
//           <ul className="flex space-x-6 text-sm">
//             <li className="hover:text-purple-400 cursor-pointer">Home</li>
//             <Link href={'/oldreport'}>
//               <li className="relative hover:text-purple-400 cursor-pointer" onClick={handleReportClick}>
//                 Reports
//                 {/* Show the notification red dot if true */}
//                 {notification && (
//                   <span className="absolute top-0 right-0 bg-red-500 text-white text-xs rounded-full w-2.5 h-2.5"></span>
//                 )}
//               </li>
//             </Link>
//             <div className="relative">
//               {/* User Dropdown */}
//               {user?.value && (
//                 <div className="relative">
//                   <MdAccountCircle
//                     className="text-2xl md:text-3xl mx-2 cursor-pointer"
//                     onClick={toggleDropdown} // Toggle on click
//                   />
//                   {dropdown && (
//                     <div className="absolute right-0 shadow-xl top-10 rounded-md w-40 border-2 border-solid border-gray-300">
//                       <ul>
//                         {/* Profile Link */}
//                         <Link href={'/profile'}><li className="hover:text-blue-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100">
//                           Profile
//                         </li></Link>
//                         {/* Logout Link */}
//                         <li
//                           onClick={Logout}
//                           className="hover:text-red-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100"
//                         >
//                           Logout
//                         </li>
//                       </ul>
//                     </div>
//                   )}
//                 </div>
//               )}

//               {/* Login button for guests */}
//               {!user?.value && (
//                 <Link href="/login">
//                   <div className="ml-4">
//                     <button className="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-opacity-50 transition ease-in-out duration-200">
//                       Login
//                     </button>
//                   </div>
//                 </Link>
//               )}
//             </div>
//           </ul>
//         </nav>

//         {/* Header Section */}
//         <div className="flex flex-col items-center text-center">
//           {/* Logo */}
//           <div style={{ height: '100vh' }}>
//       <OwlModel />
//     </div>
//           <div className="w-20 h-20 mt-5 border-2 border-white rounded-full flex items-center justify-center">
//             <img src="/Logo.png" alt="Logo" className="w-16 h-16 object-contain" />
//           </div>

//           <h1 className="text-4xl font-bold mt-4 text-pink-400">Job</h1>
//           <h2 className="text-3xl font-bold text-pink-500">Interview</h2>

//           {/* Image Section */}
//           <div className="flex justify-center mt-4 mb-4">
//             <img
//               src="/home.png"
//               alt="Job Interview"
//               className="max-w-sm w-full h-auto object-contain"
//             />
//           </div>

//           {/* Description */}
//           <p className="text-center text-gray-300 max-w-lg mx-auto">
//             Landing your dream job starts with a great interview. We provide expert tips, real-world
//             insights, and proven strategies to help you impress employers and stand out from the
//             competition.
//           </p>

//           {/* List of Services */}
//           <ul className="mt-4 text-center space-y-2 text-gray-200">
//             <li>✅ <span className="text-pink-400">Interview Preparation</span> - Master common questions.</li>
//             <li>✅ <span className="text-pink-400">Resume & Cover Letter Tips</span> - Showcase your skills.</li>
//             <li>✅ <span className="text-pink-400">Career Coaching</span> - Get expert guidance.</li>
//           </ul>

//           {/* Informational text about speech recognition */}
//           <div className="mt-6 flex justify-center pb-10">
//             <p className="text-lg font-semibold text-gray-200">
//               Please speak the phrase <span className="text-pink-500">"I am ready"</span> to proceed.
//             </p>
//           </div>
//           Speak OR Click On Get Started
//           <div className="mt-6 flex justify-center pb-10">
//             <Link href={'/role'}>
//               <button className="bg-pink-500 text-white py-3 px-6 rounded-lg text-lg font-semibold hover:bg-pink-600">
//                 GET STARTED
//               </button>
//             </Link>
//           </div>
//         </div>
//       </div>
//     </>
//   );
// }


// import { useState, useEffect, useRef } from "react";
// // import OwlModel from '../components/OwlModel'
// import Link from "next/link";
// import Head from "next/head";
// import { IoIosArrowBack } from "react-icons/io";
// import { MdAccountCircle } from 'react-icons/md';
// import { useRouter } from 'next/router'; // For programmatic navigation

// export default function Home({ Logout, user }) {
//   const [dropdown, setDropdown] = useState(false);
//   const [notification, setNotification] = useState(false); // State to track the notification
//   const router = useRouter(); // Next.js router to navigate to /role
//   const recognition = useRef(null); // Reference to the speech recognition instance
//   const [isRecognizing, setIsRecognizing] = useState(false); // To track whether recognition is ongoing
//   const [isIphone, setIsIphone] = useState(false); // State to track if the device is iPhone
// const[userr, setUserr] = useState(null);

//   const speak = (text) => {
//     const utterance = new SpeechSynthesisUtterance(text);
//     utterance.lang = 'en-US'; // Set language to English
//     window.speechSynthesis.speak(utterance);
//   };

//   useEffect(() => {
//     // Detect if the device is iPhone
//     if (/iPhone|iPad|iPod/i.test(navigator.userAgent)) {
//       setIsIphone(true);
//     }



//     // Delay speech synthesis for 1 second after page load
//     const timeoutId = setTimeout(() => {
//       // Check if the device is iOS and adjust the speech message accordingly
//       if (isIphone) {
//         const userFromStorage = JSON.parse(localStorage.getItem('user'));

//           // console.log(userFromStorage);
//           setUserr(userFromStorage);

//           // No need to speak until the user is set
//           if (userFromStorage) {
//             // Speak the instructions once user data is loaded
//             const firstName = userFromStorage?.fullName?.split(' ')[0];
//             speak(`Hey ${firstName}, welcome back! Just say 'I'm ready' when you're all set!`);
//           }
//       } else {
//         const userFromStorage = JSON.parse(localStorage.getItem('user'));

//           // console.log(userFromStorage);
//           setUserr(userFromStorage);

//           // No need to speak until the user is set
//           if (userFromStorage) {
//             // Speak the instructions once user data is loaded
//             const firstName = userFromStorage?.fullName?.split(' ')[0];
//             speak(`Hey ${firstName}, welcome back! Just say 'I'm ready' when you're all set!`);
//           } }
//     }, 1000); // Delay by 1 second after page load

//     return () => clearTimeout(timeoutId); // Cleanup timeout on component unmount
//   }, [isIphone]);

//   useEffect(() => {
//     // Initialize Speech Recognition API
//     const initSpeechRecognition = () => {
//       if (window.SpeechRecognition || window.webkitSpeechRecognition) {
//         recognition.current = new (window.SpeechRecognition || window.webkitSpeechRecognition)();
//         recognition.current.lang = "en-US";
//         recognition.current.continuous = true; // Continuous recognition
//         recognition.current.interimResults = false;

//         recognition.current.onstart = () => {
//           console.log("Speech recognition started.");
//           setIsRecognizing(true); // Set the recognizing flag to true
//         };

//         recognition.current.onend = () => {
//           console.log("Speech recognition ended.");
//           setIsRecognizing(false); // Set the recognizing flag to false

//           // Restart recognition only if it's fully ended and not already recognizing
//           if (recognition.current && !isRecognizing && recognition.current.state === "inactive") {
//             console.log("Speech recognition restarted."); // Debug log
//             recognition.current.start(); // Restart recognition
//           }
//         };

//         recognition.current.onresult = (event) => {
//           const transcript = event.results[0][0].transcript.toLowerCase();
//           console.log("Transcript: ", transcript);

//           // If the user says "I am ready", navigate to /role
//           if (transcript.includes("i am ready")) {
//             router.push("/role"); // Redirect to /role when "I am ready" is spoken
//           }
//         };

//         // Start listening when the page loads if it's not already started
//         if (recognition.current && !isRecognizing) {
//           recognition.current.start();
//         }
//       } else {
//         console.error("Speech recognition is not supported in this browser.");
//       }
//     };

//     initSpeechRecognition();

//     // Check if there’s a notification stored in localStorage when the component mounts
//     const checkStorage = () => {
//       const storedNotification = localStorage.getItem("store");
//       if (storedNotification) {
//         setNotification(true);
//       }
//     };

//     checkStorage();
//   }, [router, isRecognizing]);

//   const toggleDropdown = () => setDropdown(prev => !prev);

//   // Function to simulate storing an item in localStorage and triggering the notification
//   const handleReportClick = () => {
//     localStorage.removeItem("store"); // Remove notification from localStorage
//     setNotification(false); // Hide the notification dot
//   };

//   return (
//     <>
//       <Head>
//         <title>Shakktii Interview Trainer</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <div className="min-h-screen bg-gradient-to-b text-white px-4 bg-cover flex flex-col items-center justify-center" style={{ backgroundImage: "url('/bg.gif')" }}>
//         {/* Navigation Bar */}
//         <nav className="flex justify-between items-center py-4 px-6 bg-black bg-opacity-50 w-full">
//           <div className="text-white text-lg font-bold">Shakkti AI</div>
//           <ul className="flex space-x-6 text-sm">
//             <li className="hover:text-purple-400 cursor-pointer">Home</li>
//             <Link href={'/oldreport'}>
//               <li className="relative hover:text-purple-400 cursor-pointer" onClick={handleReportClick}>
//                 Reports
//                 {notification && (
//                   <span className="absolute top-0 right-0 bg-red-500 text-white text-xs rounded-full w-2.5 h-2.5"></span>
//                 )}
//               </li>
//             </Link>
//             <div className="relative">
//               {user?.value && (
//                 <div className="relative">
//                   <MdAccountCircle className="text-2xl md:text-3xl mx-2 cursor-pointer" onClick={toggleDropdown} />
//                   {dropdown && (
//                     <div className="absolute right-0 shadow-xl top-10 rounded-md w-40 border-2 border-solid border-gray-300">
//                       <ul>
//                         <Link href={'/profile'}>
//                           <li className="hover:text-blue-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100">Profile</li>
//                         </Link>
//                         <li onClick={Logout} className="hover:text-red-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100">Logout</li>
//                       </ul>
//                     </div>
//                   )}
//                 </div>
//               )}
//               {!user?.value && (
//                 <Link href="/login">
//                   <div className="ml-4">
//                     <button className="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-opacity-50 transition ease-in-out duration-200">Login</button>
//                   </div>
//                 </Link>
//               )}
//             </div>
//           </ul>
//         </nav>

//         {/* Header Section */}
//         <div className="flex flex-col items-center text-center">
//           {/* <div style={{ height: '100vh' }}>
//             <OwlModel  />
//           </div> */}
//           <div  className="w-20 h-20 mt-5 border-2 border-white rounded-full flex items-center justify-center">
//             <img src="/Logo.png" alt="Logo" className="w-16 h-16 object-contain" />
//           </div>
//           {isIphone && (
//           <>
//           <div onClick={() => speak(`Hey ${firstName}, welcome back! Just say 'I'm ready' when you're all set!`)}>
//           <h1  className="text-4xl font-bold mt-4 text-pink-400">Job</h1>
//           <h2  className="text-3xl font-bold text-pink-500">Interview</h2>
//           </div> </>
//          )}
//           {!isIphone && (
//           <>
//           <h1 className="text-4xl font-bold mt-4 text-pink-400">Job</h1>
//           <h2 className="text-3xl font-bold text-pink-500">Interview</h2>
//           </>
//          )}
//           <div className="flex justify-center mt-4 mb-4">
//             <img src="/home.png" alt="Job Interview" className="max-w-sm w-full h-auto object-contain" />
//           </div>

//           <p   className="text-center text-gray-300 max-w-lg mx-auto">
//             Landing your dream job starts with a great interview. We provide expert tips, real-world insights, and proven strategies to help you impress employers and stand out from the competition.
//           </p>

//           <ul className="mt-4 text-center space-y-2 text-gray-200">
//             <li>✅ <span className="text-pink-400">Interview Preparation</span> - Master common questions.</li>
//             <li>✅ <span className="text-pink-400">Resume & Cover Letter Tips</span> - Showcase your skills.</li>
//             <li>✅ <span className="text-pink-400">Career Coaching</span> - Get expert guidance.</li>
//           </ul>

//           <div className="mt-6 flex justify-center pb-10">
//             <p className="text-lg font-semibold text-gray-200">
//               Please speak the phrase <span className="text-pink-500">"I am ready"</span> to proceed.
//             </p>
//           </div>

//           {/* Only show the button for iPhone users */}
//           {isIphone && (
//             <div className="mt-6 flex justify-center pb-10">
//               <button
//                 className="bg-pink-500 text-white py-3 px-6 rounded-lg text-lg font-semibold hover:bg-pink-600"

//               >
//                 TAP TO CONTINUE
//               </button>
//             </div>
//           )}

//           {/* GET STARTED button */}

//             <div className="mt-6 flex justify-center pb-10">
//               <Link href={'/role'}>
//                 <button className="bg-pink-500 text-white py-3 px-6 rounded-lg text-lg font-semibold hover:bg-pink-600">
//                   GET STARTED
//                 </button>
//               </Link>
//             </div>

//         </div>
//       </div>
//     </>
//   );
// }


import { useState, useEffect, useRef } from "react";
import Link from "next/link";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from 'next/router'; // For programmatic navigation

export default function Home() {
  const [selected, setSelected] = useState(null);
  const plans = [
    { title: '8th to 12th', price: 99 },
    { title: 'Graduate', price: 99 },
    { title: 'Post Graduate', price: 99 },
    { title: 'Competitive', price: 99 },
    { title: 'Professional', price: 99 },
  ];
  const features = [
    "5 Mock Interviews",
    "✅ Interview Reports",
    "✅ Chat Support (+Rs 99)",
    "✅ YouTube Video Suggestions",
    "✅ Detailed Score Progress",
    "✅ Performance Analysis",
    "✅ Score by Job Role",
    "✅ Comparison Interviews",
    "✅ Detailed Analysis",
    "✅ Test 20 (Personality & Academic Test)",
  ];
  return (
    <>
      <Head>
        <title>Shakktii Interview Trainer</title>
        <meta name="description" content="Empower your learning journey through skill analysis, real-time chats, and gamified challenges to prepare for mock interviews — with MockMingle" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="min-h-screen  px-12  bg-cover  items-center justify-center overflow-x-hidden sm:overflow-x-hidden">
       


          {/* Text content section */}
          <div className="col-span-1 lg:col-span-2 mt-4 pt-10  order-2 lg:order-1 flex flex-col items-center justify-center">
            <h1 className="text-4xl m-6 md:m-10 font-bold text-shadow-lg " >Your Journey from Learning to Leading Starts Here</h1>
            <p className="text-2xl m-6 md:m-10 font-semibold  " >Empower your learning journey through skill analysis, real-time chats, and gamified challenges to prepare for mock interviews — with&nbsp;MockMingle</p>
            <div className="flex justify-center rounded-full  w-full">
              <Link href={'/language'}><button className="shadow-[0px_0px_5px_5px_rgba(0,0,0,0.10)]  w-[42rem]  text-black py-3 px-6 rounded-full text-lg font-semibold bg-white hover:bg-blue-400 hover:text-white transition duration-300">
                Get Started
              </button></Link>
            </div>
           
          </div>
        
      </div>


      <div id="feature" className="overflow-x-hidden mt-[-6rem] w-full rounded-t-[6.188rem] shadow-[0px_-7px_15.1px_0px_#FFFFFF] bg-[linear-gradient(180.29deg,#D3E7F6_6.63%,#000000_150.86%)] px-4 sm:px-10 py-10">
        {/* Heading */}
       
        {/* Cards */}
        
        
        <div className="relative mt-10 lg:m-40 grid grid-cols-1 lg:grid-cols-2 " style={{ perspective: "1000px" }}>
          <div
            className="transform rounded-lg gap-10"
            style={{
              transform: "rotateY(50deg)",
              transformStyle: "preserve-3d",
            }}
          >
            <img
              src="/p1.jpeg"
              width={300}

              alt="Preparation is the key"
              className="rounded-lg h-40 shadow-2xl border border-white border-4 shadow-gray-300"
            />
          </div>

          <div className="mt-4">
            <div className="flex items-center gap-2">
              <span className="bg-white text-black border border-black px-3 py-1 rounded-full text-sm">1</span>
              <h2 className="text-xl font-semibold text-black">Try Your Practice</h2>
            </div>
            <p className="text-black font-semibold mt-2 text-sm leading-relaxed">
              Test your interview skills, identify weaknesses, and refine your responses in a risk-free environment. Boost your confidence and reduce interview anxiety before the real challenge!
            </p>
          </div>
        </div>


        <div
          className="relative lg:m-40 mt-10 grid grid-cols-1 lg:grid-cols-2"
          style={{ perspective: "1000px" }}
        >
          {/* Image Section */}
          <div
            className="transform rounded-lg mr-10  sm:order-first lg:order-last"
            style={{
              transform: "rotateY(330deg)",
              transformStyle: "preserve-3d",
            }}
          >
            <img
              src="/p2.jpeg"
              width={300}
              alt="Preparation is the key"
              className="rounded-lg h-40 lg:ml-32 border border-white border-4 shadow-2xl order-1 shadow-gray-300"
            />
          </div>

          {/* Text Section */}
          <div className="mt-4">
            <div className="flex items-center gap-2">
              <span className="bg-white border border-black text-black px-3 py-1 rounded-full text-sm">2</span>
              <h2 className="text-xl font-semibold text-black">Real-time Interview Practice Conducted by AI</h2>
            </div>
            <p className="text-black font-semibold mt-2 text-sm leading-relaxed">
              Get live, AI-driven mock interviews with instant feedback on tone, confidence, and accuracy, saving time with data-driven insights.
            </p>
          </div>
        </div>




        <div className="relative mt-10 lg:m-40 grid grid-cols-1 lg:grid-cols-2 " style={{ perspective: "1000px" }}>
          <div
            className="transform rounded-lg"
            style={{
              transform: "rotateY(50deg)",
              transformStyle: "preserve-3d",
            }}
          >
            <img
              src="/p3.jpg"
              width={300}

              alt="Preparation is the key"
              className="rounded-lg h-40 shadow-2xl border border-white border-4 shadow-gray-700"
            />
          </div>

          <div className="mt-4">
            <div className="flex items-center gap-2">
              <span className="bg-white border border-black text-black px-3 py-1 rounded-full text-sm">3</span>
              <h2 className="text-xl font-semibold text-black">Flexible Interview Timing</h2>
            </div>
            <p className="text-black font-semibold mt-2 text-sm leading-relaxed">
              Practice Anytime, Anywhere – No fixed schedules, instant access for busy students and professionals, ensuring stress-free, flexible preparation.
            </p>
          </div>
        </div>


        <div
          className="relative lg:m-40 mt-10 grid grid-cols-1 lg:grid-cols-2"
          style={{ perspective: "1000px" }}
        >
          {/* Image Section */}
          <div
            className="transform rounded-lg lg:ml-32 mr-10 sm:order-first lg:order-last"
            style={{
              transform: "rotateY(330deg)",
              transformStyle: "preserve-3d",
            }}
          >
            <img
              src="/p4.png"
              width={300}
              alt="Preparation is the key"
              className="rounded-lg h-40 shadow-2xl order-1 border border-white border-4 shadow-gray-800"
            />
          </div>

          {/* Text Section */}
          <div className="mt-4">
            <div className="flex items-center gap-2">
              <span className="bg-white border border-black text-black px-3 py-1 rounded-full text-sm">4</span>
              <h2 className="text-xl font-semibold text-black">Gamified Experience</h2>
            </div>
            <p className="text-black font-semibold mt-2 text-sm leading-relaxed">
              MockMingle uses gamification with scores, badges, and leaderboards to make learning fun, motivating, and rewarding while tracking your progress.
            </p>
          </div>
        </div>

        <div className="relative mt-10 lg:m-40 grid grid-cols-1 lg:grid-cols-2 " style={{ perspective: "1000px" }}>
          <div
            className="transform rounded-lg"
            style={{
              transform: "rotateY(50deg)",
              transformStyle: "preserve-3d",
            }}
          >
            <img
              src="/p5.png"
              width={300}

              alt="Preparation is the key"
              className="rounded-lg h-40 shadow-2xl border border-white border-4 shadow-gray-700"
            />
          </div>

          <div className="mt-4">
            <div className="flex items-center gap-2">
              <span className="bg-white border border-black text-black px-3 py-1 rounded-full text-sm">5</span>
              <h2 className="text-xl font-semibold text-black"> Get Expert Feedback</h2>
            </div>
            <p className="text-black font-semibold mt-2 text-sm leading-relaxed">
              Get detailed insights from AI and industry experts on communication, technical skills, and performance, with personalized improvement suggestions for better interview success.
            </p>
          </div>
        </div>


        <div
          className="relative lg:m-40 mt-10 grid grid-cols-1 lg:grid-cols-2"
          style={{ perspective: "1000px" }}
        >
          {/* Image Section */}
          <div
            className="transform rounded-lg mr-10 lg:ml-32 sm:order-first lg:order-last"
            style={{
              transform: "rotateY(330deg)",
              transformStyle: "preserve-3d",
            }}
          >
            <img
              src="/p6.jpg"
              width={300}
              alt="Preparation is the key"
              className="rounded-lg h-40 shadow-2xl border border-white border-4 order-1 shadow-gray-800"
            />
          </div>

          {/* Text Section */}
          <div className="mt-4">
            <div className="flex items-center gap-2">
              <span className="bg-white text-black border border-black px-3 py-1 rounded-full text-sm">6</span>
              <h2 className="text-xl font-bold text-black">Get Suggestions in Video Format
              </h2>
            </div>
            <p className="text-black font-semibold mt-2 text-sm leading-relaxed">
              Get AI-driven or expert video suggestions with step-by-step guidance on answers, posture, and tone for easier, more engaging improvement.
            </p>
          </div>
        </div>



        
      </div>
      <footer id="contact" className=" h-[15rem] md:h-[24rem] overflow-y-hidden overflow-x-hidden">

        <div className="">
          {/* <div>
            <img src="/blue_mascot_down.png" alt="" className="h-[16rem] md:h-[25rem] -mt-[1rem] -mb-[15rem] -pb-[10rem] w-[auto]" />
          </div> */}
          <div className="    ">
            <h1 className=" rounded-full text-center w-32 mt-5 m-auto">Contact Us</h1>
            <h2
              className="text-2xl lg:text-2xl text-center font-bold  py-4 "
              style={{
                fontFamily: "Arial, sans-serif",
                backgroundColor: "white",
                
                textShadow: "2px 2px 3px rgba(0, 0, 0, 0.7)",
                WebkitBackgroundClip: "text",
                backgroundClip: "text",
              }}
            >
              connect@mockmingle.in
            </h2>
            <div className="flex justify-around mt-20">

              <h2 className=" border-2 p-2 rounded-full">Terms & Conditions</h2>
              <h2 className=" border-2 p-2 rounded-full">Privacy Policy</h2>
              
            </div>

          </div>
        </div>
        <p className=" flex justify-center mt-24 ">powered by&nbsp;<span className="text-blue-300 font-bold"> Shakktii.in</span></p>
      </footer>

    </>
  );
}