


// import { useState, useEffect, useRef } from "react";
// import Head from "next/head";
// import { getApiResponse } from './api/response';
// import Link from "next/link";
// import { IoIosArrowBack } from "react-icons/io";
// import { MdAccountCircle } from 'react-icons/md';

// export default function Home({ Logout, user }) {
//   const [dropdown, setDropdown] = useState(false);
//   const [notification, setNotification] = useState(false); // State to track the notification
//   const [isStored, setIsStored] = useState(false); // To track if the item is successfully stored in localStorage

//   useEffect(() => {
//     // Request microphone (audio) access
//     const requestPermissions = async () => {
//       try {
//         // Requesting audio permission (microphone)
//         await navigator.mediaDevices.getUserMedia({ audio: true, sound: true });
//         console.log("Microphone and sound access granted.");
//       } catch (err) {
//         console.error("Microphone and sound access denied:", err);
//         // Optionally, show an alert or message to the user about the permission issue
//       }
//     };

//     requestPermissions();

//     // Check if there’s a notification stored in localStorage when the component mounts
//     const checkStorage = () => {
//       const storedNotification = localStorage.getItem("store");
//       if (storedNotification) {
//         setNotification(true);
//       }
//     };

//     checkStorage();
//   }, []);

//   const toggleDropdown = () => setDropdown(prev => !prev);

//   // Function to simulate storing an item in localStorage and triggering the notification
//   const handleReportClick = () => {
//     localStorage.removeItem("store"); // Remove notification from localStorage
//     setNotification(false); // Hide the notification dot
//   };

//   return (<><Head>
//     <title>Shakktii Interview Trainer</title>
//     <meta name="description" content="Generated by create next app" />
//     <meta name="viewport" content="width=device-width, initial-scale=1" />
//     <link rel="icon" href="/favicon.ico" />
//   </Head>
//     <div className="min-h-screen bg-gradient-to-b text-white px-4 bg-cover flex flex-col items-center justify-center" style={{ backgroundImage: "url('/bg.gif')" }}>
//       {/* Navigation Bar */}
//       <nav className="flex justify-between items-center py-4 px-6 bg-black bg-opacity-50 w-full">
//         <div className="text-white text-lg font-bold">Shaktti AI</div>
//         <ul className="flex space-x-6 text-sm">
//           <li className="hover:text-purple-400 cursor-pointer">Home</li>
//           <Link href={'/oldreport'}>
//             <li className="relative hover:text-purple-400 cursor-pointer" onClick={handleReportClick}>
//               Reports
//               {/* Show the notification red dot if true */}
//               {notification && (
//                 <span className="absolute top-0 right-0 bg-red-500 text-white text-xs rounded-full w-2.5 h-2.5"></span>
//               )}
//             </li>
//           </Link>
//           <div className="relative">
//             {/* User Dropdown */}
//             {user?.value && (
//               <div className="relative">
//                 <MdAccountCircle
//                   className="text-2xl md:text-3xl mx-2 cursor-pointer"
//                   onClick={toggleDropdown} // Toggle on click
//                 />
//                 {dropdown && (
//                   <div className="absolute right-0 shadow-xl top-10 rounded-md w-40 border-2 border-solid border-gray-300">
//                     <ul>
//                       {/* Profile Link */}
//                       <Link href={'/profile'}><li className="hover:text-blue-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100">
//                         Profile
//                       </li></Link>
//                       {/* Logout Link */}
//                       <li
//                         onClick={Logout}
//                         className="hover:text-red-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100"
//                       >
//                         Logout
//                       </li>
//                     </ul>
//                   </div>
//                 )}
//               </div>
//             )}

//             {/* Login button for guests */}
//             {!user?.value && (
//               <Link href="/login">
//                 <div className="ml-4">
//                   <button className="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-opacity-50 transition ease-in-out duration-200">
//                     Login
//                   </button>
//                 </div>
//               </Link>
//             )}
//           </div>
//         </ul>
//       </nav>

//       {/* Header Section */}
//       <div className="flex flex-col items-center text-center">
//         {/* Logo */}
//         <div className="w-20 h-20 mt-5 border-2 border-white rounded-full flex items-center justify-center">
//           <img src="/Logo.png" alt="Logo" className="w-16 h-16 object-contain" />
//         </div>

//         <h1 className="text-4xl font-bold mt-4 text-pink-400">Job</h1>
//         <h2 className="text-3xl font-bold text-pink-500">Interview</h2>

//         {/* Image Section */}
//         <div className="flex justify-center mt-4 mb-4">
//           <img
//             src="/home.png"
//             alt="Job Interview"
//             className="max-w-sm w-full h-auto object-contain"
//           />
//         </div>

//         {/* Description */}
//         <p className="text-center text-gray-300 max-w-lg mx-auto">
//           Landing your dream job starts with a great interview. We provide expert tips, real-world
//           insights, and proven strategies to help you impress employers and stand out from the
//           competition.
//         </p>

//         {/* List of Services */}
//         <ul className="mt-4 text-center space-y-2 text-gray-200">
//           <li>✅ <span className="text-pink-400">Interview Preparation</span> - Master common questions.</li>
//           <li>✅ <span className="text-pink-400">Resume & Cover Letter Tips</span> - Showcase your skills.</li>
//           <li>✅ <span className="text-pink-400">Career Coaching</span> - Get expert guidance.</li>
//         </ul>

//         {/* Call to Action Button */}
//         <div className="mt-6 flex justify-center pb-10">
//           <Link href={'/role'}>
//             <button className="bg-pink-500 text-white py-3 px-6 rounded-lg text-lg font-semibold hover:bg-pink-600">
//               GET STARTED
//             </button>
//           </Link>
//         </div>
//       </div>
//     </div>
//     </>
//   );
// }

// import { useState, useEffect, useRef } from "react";
// import Head from "next/head";
// import Link from "next/link";
// import { useRouter } from 'next/router'; // For programmatic navigation
// import { IoIosArrowBack } from "react-icons/io";
// import { MdAccountCircle } from 'react-icons/md';

// export default function Home({ Logout, user }) {
//   const [dropdown, setDropdown] = useState(false);
//   const [notification, setNotification] = useState(false); // State to track the notification
//   const [isStored, setIsStored] = useState(false); // To track if the item is successfully stored in localStorage
//   const [speechRecognizing, setSpeechRecognizing] = useState(false); // State to track speech recognition status
//   const router = useRouter(); // Next.js router to navigate to /role

//   const recognition = useRef(null); // Reference to the speech recognition instance

//   useEffect(() => {
//     // Initialize Speech Recognition API
//     const initSpeechRecognition = () => {
//       if (window.SpeechRecognition || window.webkitSpeechRecognition) {
//         recognition.current = new (window.SpeechRecognition || window.webkitSpeechRecognition)();
//         recognition.current.lang = "en-US";
//         recognition.current.continuous = false;
//         recognition.current.interimResults = false;

//         recognition.current.onstart = () => {
//           console.log("Speech recognition started.");
//           setSpeechRecognizing(true);
//         };

//         recognition.current.onend = () => {
//           console.log("Speech recognition ended.");
//           setSpeechRecognizing(false);
//         };

//         recognition.current.onresult = (event) => {
//           const transcript = event.results[0][0].transcript.toLowerCase();
//           console.log("Transcript: ", transcript);

//           if (transcript.includes("i am ready")) {
//             router.push("/role"); // Redirect to /role when "I am ready" is spoken
//           }
//         };
//       } else {
//         console.error("Speech recognition is not supported in this browser.");
//       }
//     };

//     initSpeechRecognition();

//     // Check if there’s a notification stored in localStorage when the component mounts
//     const checkStorage = () => {
//       const storedNotification = localStorage.getItem("store");
//       if (storedNotification) {
//         setNotification(true);
//       }
//     };

//     checkStorage();
//   }, [router]);

//   const toggleDropdown = () => setDropdown(prev => !prev);

//   // Function to simulate storing an item in localStorage and triggering the notification
//   const handleReportClick = () => {
//     localStorage.removeItem("store"); // Remove notification from localStorage
//     setNotification(false); // Hide the notification dot
//   };

//   // Start the speech recognition when the component mounts or when the user clicks a button
//   const startRecognition = () => {
//     if (recognition.current) {
//       recognition.current.start(); // Start listening to the user's speech
//     }
//   };

//   return (
//     <>
//       <Head>
//         <title>Shakktii Interview Trainer</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <div className="min-h-screen bg-gradient-to-b text-white px-4 bg-cover flex flex-col items-center justify-center" style={{ backgroundImage: "url('/bg.gif')" }}>
//         {/* Navigation Bar */}
//         <nav className="flex justify-between items-center py-4 px-6 bg-black bg-opacity-50 w-full">
//           <div className="text-white text-lg font-bold">Shaktti AI</div>
//           <ul className="flex space-x-6 text-sm">
//             <li className="hover:text-purple-400 cursor-pointer">Home</li>
//             <Link href={'/oldreport'}>
//               <li className="relative hover:text-purple-400 cursor-pointer" onClick={handleReportClick}>
//                 Reports
//                 {/* Show the notification red dot if true */}
//                 {notification && (
//                   <span className="absolute top-0 right-0 bg-red-500 text-white text-xs rounded-full w-2.5 h-2.5"></span>
//                 )}
//               </li>
//             </Link>
//             <div className="relative">
//               {/* User Dropdown */}
//               {user?.value && (
//                 <div className="relative">
//                   <MdAccountCircle
//                     className="text-2xl md:text-3xl mx-2 cursor-pointer"
//                     onClick={toggleDropdown} // Toggle on click
//                   />
//                   {dropdown && (
//                     <div className="absolute right-0 shadow-xl top-10 rounded-md w-40 border-2 border-solid border-gray-300">
//                       <ul>
//                         {/* Profile Link */}
//                         <Link href={'/profile'}><li className="hover:text-blue-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100">
//                           Profile
//                         </li></Link>
//                         {/* Logout Link */}
//                         <li
//                           onClick={Logout}
//                           className="hover:text-red-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100"
//                         >
//                           Logout
//                         </li>
//                       </ul>
//                     </div>
//                   )}
//                 </div>
//               )}

//               {/* Login button for guests */}
//               {!user?.value && (
//                 <Link href="/login">
//                   <div className="ml-4">
//                     <button className="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-opacity-50 transition ease-in-out duration-200">
//                       Login
//                     </button>
//                   </div>
//                 </Link>
//               )}
//             </div>
//           </ul>
//         </nav>

//         {/* Header Section */}
//         <div className="flex flex-col items-center text-center">
//           {/* Logo */}
//           <div className="w-20 h-20 mt-5 border-2 border-white rounded-full flex items-center justify-center">
//             <img src="/Logo.png" alt="Logo" className="w-16 h-16 object-contain" />
//           </div>

//           <h1 className="text-4xl font-bold mt-4 text-pink-400">Job</h1>
//           <h2 className="text-3xl font-bold text-pink-500">Interview</h2>

//           {/* Image Section */}
//           <div className="flex justify-center mt-4 mb-4">
//             <img
//               src="/home.png"
//               alt="Job Interview"
//               className="max-w-sm w-full h-auto object-contain"
//             />
//           </div>

//           {/* Description */}
//           <p className="text-center text-gray-300 max-w-lg mx-auto">
//             Landing your dream job starts with a great interview. We provide expert tips, real-world
//             insights, and proven strategies to help you impress employers and stand out from the
//             competition.
//           </p>

//           {/* List of Services */}
//           <ul className="mt-4 text-center space-y-2 text-gray-200">
//             <li>✅ <span className="text-pink-400">Interview Preparation</span> - Master common questions.</li>
//             <li>✅ <span className="text-pink-400">Resume & Cover Letter Tips</span> - Showcase your skills.</li>
//             <li>✅ <span className="text-pink-400">Career Coaching</span> - Get expert guidance.</li>
//           </ul>

//           {/* Call to Action Button */}
//           <div className="mt-6 flex justify-center pb-10">
//             {/* Replacing the button with speech recognition trigger */}
//             {!speechRecognizing && (
//               <button
//                 onClick={startRecognition}
//                 className="bg-pink-500 text-white py-3 px-6 rounded-lg text-lg font-semibold hover:bg-pink-600"
//               >
//                 Speak "I am ready" to Get Started
//               </button>
//             )}
//           </div>
//         </div>
//       </div>
//     </>
//   );
// }

// import { useState, useEffect, useRef } from "react";
// import Head from "next/head";
// import Link from "next/link";
// import { useRouter } from 'next/router'; // For programmatic navigation
// import { IoIosArrowBack } from "react-icons/io";
// import { MdAccountCircle } from 'react-icons/md';

// export default function Home({ Logout, user }) {
//   const [dropdown, setDropdown] = useState(false);
//   const [notification, setNotification] = useState(false); // State to track the notification
//   const [isStored, setIsStored] = useState(false); // To track if the item is successfully stored in localStorage
//   const [speechRecognizing, setSpeechRecognizing] = useState(false); // State to track speech recognition status
//   const router = useRouter(); // Next.js router to navigate to /role

//   const recognition = useRef(null); // Reference to the speech recognition instance

//   useEffect(() => {
//     // Initialize Speech Recognition API
//     const initSpeechRecognition = () => {
//       if (window.SpeechRecognition || window.webkitSpeechRecognition) {
//         recognition.current = new (window.SpeechRecognition || window.webkitSpeechRecognition)();
//         recognition.current.lang = "en-US";
//         recognition.current.continuous = true; // Continuous recognition
//         recognition.current.interimResults = false;

//         recognition.current.onstart = () => {
//           console.log("Speech recognition started.");
//           setSpeechRecognizing(true);
//         };

//         recognition.current.onend = () => {
//           console.log("Speech recognition ended.");
//           setSpeechRecognizing(false);
//         };

//         recognition.current.onresult = (event) => {
//           const transcript = event.results[0][0].transcript.toLowerCase();
//           console.log("Transcript: ", transcript);

//           if (transcript.includes("i am ready")) {
//             router.push("/role"); // Redirect to /role when "I am ready" is spoken
//           }
//         };

//         // Start listening when the page loads
//         recognition.current.start();
//       } else {
//         console.error("Speech recognition is not supported in this browser.");
//       }
//     };

//     initSpeechRecognition();

//     // Check if there’s a notification stored in localStorage when the component mounts
//     const checkStorage = () => {
//       const storedNotification = localStorage.getItem("store");
//       if (storedNotification) {
//         setNotification(true);
//       }
//     };

//     checkStorage();
//   }, [router]);

//   const toggleDropdown = () => setDropdown(prev => !prev);

//   // Function to simulate storing an item in localStorage and triggering the notification
//   const handleReportClick = () => {
//     localStorage.removeItem("store"); // Remove notification from localStorage
//     setNotification(false); // Hide the notification dot
//   };

//   return (
//     <>
//       <Head>
//         <title>Shakktii Interview Trainer</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <div className="min-h-screen bg-gradient-to-b text-white px-4 bg-cover flex flex-col items-center justify-center" style={{ backgroundImage: "url('/bg.gif')" }}>
//         {/* Navigation Bar */}
//         <nav className="flex justify-between items-center py-4 px-6 bg-black bg-opacity-50 w-full">
//           <div className="text-white text-lg font-bold">Shaktti AI</div>
//           <ul className="flex space-x-6 text-sm">
//             <li className="hover:text-purple-400 cursor-pointer">Home</li>
//             <Link href={'/oldreport'}>
//               <li className="relative hover:text-purple-400 cursor-pointer" onClick={handleReportClick}>
//                 Reports
//                 {/* Show the notification red dot if true */}
//                 {notification && (
//                   <span className="absolute top-0 right-0 bg-red-500 text-white text-xs rounded-full w-2.5 h-2.5"></span>
//                 )}
//               </li>
//             </Link>
//             <div className="relative">
//               {/* User Dropdown */}
//               {user?.value && (
//                 <div className="relative">
//                   <MdAccountCircle
//                     className="text-2xl md:text-3xl mx-2 cursor-pointer"
//                     onClick={toggleDropdown} // Toggle on click
//                   />
//                   {dropdown && (
//                     <div className="absolute right-0 shadow-xl top-10 rounded-md w-40 border-2 border-solid border-gray-300">
//                       <ul>
//                         {/* Profile Link */}
//                         <Link href={'/profile'}><li className="hover:text-blue-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100">
//                           Profile
//                         </li></Link>
//                         {/* Logout Link */}
//                         <li
//                           onClick={Logout}
//                           className="hover:text-red-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100"
//                         >
//                           Logout
//                         </li>
//                       </ul>
//                     </div>
//                   )}
//                 </div>
//               )}

//               {/* Login button for guests */}
//               {!user?.value && (
//                 <Link href="/login">
//                   <div className="ml-4">
//                     <button className="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-opacity-50 transition ease-in-out duration-200">
//                       Login
//                     </button>
//                   </div>
//                 </Link>
//               )}
//             </div>
//           </ul>
//         </nav>

//         {/* Header Section */}
//         <div className="flex flex-col items-center text-center">
//           {/* Logo */}
//           <div className="w-20 h-20 mt-5 border-2 border-white rounded-full flex items-center justify-center">
//             <img src="/Logo.png" alt="Logo" className="w-16 h-16 object-contain" />
//           </div>

//           <h1 className="text-4xl font-bold mt-4 text-pink-400">Job</h1>
//           <h2 className="text-3xl font-bold text-pink-500">Interview</h2>

//           {/* Image Section */}
//           <div className="flex justify-center mt-4 mb-4">
//             <img
//               src="/home.png"
//               alt="Job Interview"
//               className="max-w-sm w-full h-auto object-contain"
//             />
//           </div>

//           {/* Description */}
//           <p className="text-center text-gray-300 max-w-lg mx-auto">
//             Landing your dream job starts with a great interview. We provide expert tips, real-world
//             insights, and proven strategies to help you impress employers and stand out from the
//             competition.
//           </p>

//           {/* List of Services */}
//           <ul className="mt-4 text-center space-y-2 text-gray-200">
//             <li>✅ <span className="text-pink-400">Interview Preparation</span> - Master common questions.</li>
//             <li>✅ <span className="text-pink-400">Resume & Cover Letter Tips</span> - Showcase your skills.</li>
//             <li>✅ <span className="text-pink-400">Career Coaching</span> - Get expert guidance.</li>
//           </ul>

//           {/* Informational text about speech recognition */}
//           <div className="mt-6 flex justify-center pb-10">
//             <p className="text-lg font-semibold text-gray-200">
//               Please speak the phrase <span className="text-pink-500">"I am ready"</span> to proceed.
//             </p>
//           </div>
//         </div>
//       </div>
//     </>
//   );
// }


// import { useState, useEffect, useRef } from "react";
// import Link from "next/link";
// import Head from "next/head";
// import { IoIosArrowBack } from "react-icons/io";
// import { MdAccountCircle } from 'react-icons/md';
// import { useRouter } from 'next/router'; // For programmatic navigation

// export default function Home({ Logout, user }) {
//   const [dropdown, setDropdown] = useState(false);
//   const [notification, setNotification] = useState(false); // State to track the notification
//   const router = useRouter(); // Next.js router to navigate to /role

//   const recognition = useRef(null); // Reference to the speech recognition instance

//   useEffect(() => {
//     // Initialize Speech Recognition API
//     const initSpeechRecognition = () => {
//       if (window.SpeechRecognition || window.webkitSpeechRecognition) {
//         recognition.current = new (window.SpeechRecognition || window.webkitSpeechRecognition)();
//         recognition.current.lang = "en-US";
//         recognition.current.continuous = true; // Continuous recognition
//         recognition.current.interimResults = false;

//         recognition.current.onstart = () => {
//           console.log("Speech recognition started.");
//         };

//         recognition.current.onend = () => {
//           console.log("Speech recognition ended.");
//           if(!recognition.current.onstart){

//         }
//           // You can try to restart recognition only if it's completely ended.
//           // No need to call start() here if it's already restarted before
//         };

//         recognition.current.onresult = (event) => {
//           const transcript = event.results[0][0].transcript.toLowerCase();
//           console.log("Transcript: ", transcript);

//           if (transcript.includes("i am ready")) {
//             router.push("/role"); // Redirect to /role when "I am ready" is spoken
//           }
//         };

//         // Start listening when the page loads
//         recognition.current.start();
//       } else {
//         console.error("Speech recognition is not supported in this browser.");
//       }
//     };

//     initSpeechRecognition();

//     // Check if there’s a notification stored in localStorage when the component mounts
//     const checkStorage = () => {
//       const storedNotification = localStorage.getItem("store");
//       if (storedNotification) {
//         setNotification(true);
//       }
//     };

//     checkStorage();
//   }, [router]);

//   const toggleDropdown = () => setDropdown(prev => !prev);

//   // Function to simulate storing an item in localStorage and triggering the notification
//   const handleReportClick = () => {
//     localStorage.removeItem("store"); // Remove notification from localStorage
//     setNotification(false); // Hide the notification dot
//   };

//   return (
//     <>
//       <Head>
//         <title>Shakktii Interview Trainer</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <div className="min-h-screen bg-gradient-to-b text-white px-4 bg-cover flex flex-col items-center justify-center" style={{ backgroundImage: "url('/bg.gif')" }}>
//         {/* Navigation Bar */}
//         <nav className="flex justify-between items-center py-4 px-6 bg-black bg-opacity-50 w-full">
//           <div className="text-white text-lg font-bold">Shaktti AI</div>
//           <ul className="flex space-x-6 text-sm">
//             <li className="hover:text-purple-400 cursor-pointer">Home</li>
//             <Link href={'/oldreport'}>
//               <li className="relative hover:text-purple-400 cursor-pointer" onClick={handleReportClick}>
//                 Reports
//                 {/* Show the notification red dot if true */}
//                 {notification && (
//                   <span className="absolute top-0 right-0 bg-red-500 text-white text-xs rounded-full w-2.5 h-2.5"></span>
//                 )}
//               </li>
//             </Link>
//             <div className="relative">
//               {/* User Dropdown */}
//               {user?.value && (
//                 <div className="relative">
//                   <MdAccountCircle
//                     className="text-2xl md:text-3xl mx-2 cursor-pointer"
//                     onClick={toggleDropdown} // Toggle on click
//                   />
//                   {dropdown && (
//                     <div className="absolute right-0 shadow-xl top-10 rounded-md w-40 border-2 border-solid border-gray-300">
//                       <ul>
//                         {/* Profile Link */}
//                         <Link href={'/profile'}><li className="hover:text-blue-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100">
//                           Profile
//                         </li></Link>
//                         {/* Logout Link */}
//                         <li
//                           onClick={Logout}
//                           className="hover:text-red-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100"
//                         >
//                           Logout
//                         </li>
//                       </ul>
//                     </div>
//                   )}
//                 </div>
//               )}

//               {/* Login button for guests */}
//               {!user?.value && (
//                 <Link href="/login">
//                   <div className="ml-4">
//                     <button className="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-opacity-50 transition ease-in-out duration-200">
//                       Login
//                     </button>
//                   </div>
//                 </Link>
//               )}
//             </div>
//           </ul>
//         </nav>

//         {/* Header Section */}
//         <div className="flex flex-col items-center text-center">
//           {/* Logo */}
//           <div className="w-20 h-20 mt-5 border-2 border-white rounded-full flex items-center justify-center">
//             <img src="/Logo.png" alt="Logo" className="w-16 h-16 object-contain" />
//           </div>

//           <h1 className="text-4xl font-bold mt-4 text-pink-400">Job</h1>
//           <h2 className="text-3xl font-bold text-pink-500">Interview</h2>

//           {/* Image Section */}
//           <div className="flex justify-center mt-4 mb-4">
//             <img
//               src="/home.png"
//               alt="Job Interview"
//               className="max-w-sm w-full h-auto object-contain"
//             />
//           </div>

//           {/* Description */}
//           <p className="text-center text-gray-300 max-w-lg mx-auto">
//             Landing your dream job starts with a great interview. We provide expert tips, real-world
//             insights, and proven strategies to help you impress employers and stand out from the
//             competition.
//           </p>

//           {/* List of Services */}
//           <ul className="mt-4 text-center space-y-2 text-gray-200">
//             <li>✅ <span className="text-pink-400">Interview Preparation</span> - Master common questions.</li>
//             <li>✅ <span className="text-pink-400">Resume & Cover Letter Tips</span> - Showcase your skills.</li>
//             <li>✅ <span className="text-pink-400">Career Coaching</span> - Get expert guidance.</li>
//           </ul>

//           {/* Informational text about speech recognition */}
//           <div className="mt-6 flex justify-center pb-10">
//             <p className="text-lg font-semibold text-gray-200">
//               Please speak the phrase <span className="text-pink-500">"I am ready"</span> to proceed.
//             </p>
//           </div>
//         </div>
//       </div>
//     </>
//   );
// }



// import { useState, useEffect, useRef } from "react";
// import Link from "next/link";
// import Head from "next/head";
// import { IoIosArrowBack } from "react-icons/io";
// import { MdAccountCircle } from 'react-icons/md';
// import { useRouter } from 'next/router'; // For programmatic navigation



// export default function Home({ Logout, user }) {
//   const [dropdown, setDropdown] = useState(false);
//   const [notification, setNotification] = useState(false); // State to track the notification
//   const router = useRouter(); // Next.js router to navigate to /role
//   const recognition = useRef(null); // Reference to the speech recognition instance
//   const [isRecognizing, setIsRecognizing] = useState(false); // To track whether recognition is ongoing

//   useEffect(() => {
//     // Initialize Speech Recognition API
//     const initSpeechRecognition = () => {
//       if (window.SpeechRecognition || window.webkitSpeechRecognition) {
//         recognition.current = new (window.SpeechRecognition || window.webkitSpeechRecognition)();
//         recognition.current.lang = "en-US";
//         recognition.current.continuous = true; // Continuous recognition
//         recognition.current.interimResults = false;

//         recognition.current.onstart = () => {
//           console.log("Speech recognition started.");
//           setIsRecognizing(true); // Set the recognizing flag to true
//         };

//         recognition.current.onend = () => {
//           console.log("Speech recognition ended.");
//           setIsRecognizing(false); // Set the recognizing flag to false

//           // Restart recognition only if it's fully ended and not already recognizing
//           if (recognition.current && !isRecognizing && recognition.current.state === "inactive") {
//             console.log("Speech recognition restarted."); // Debug log
//             recognition.current.start(); // Restart recognition
//           }
//         };

//         recognition.current.onresult = (event) => {
//           const transcript = event.results[0][0].transcript.toLowerCase();
//           console.log("Transcript: ", transcript);

//           // If the user says "I am ready", navigate to /role
//           if (transcript.includes("i am ready")) {
//             router.push("/role"); // Redirect to /role when "I am ready" is spoken
//           }
//         };

//         // Start listening when the page loads if it's not already started
//         if (recognition.current && !isRecognizing) {
//           recognition.current.start();
//         }
//       } else {
//         console.error("Speech recognition is not supported in this browser.");
//       }
//     };

//     initSpeechRecognition();

//     // Check if there’s a notification stored in localStorage when the component mounts
//     const checkStorage = () => {
//       const storedNotification = localStorage.getItem("store");
//       if (storedNotification) {
//         setNotification(true);
//       }
//     };

//     checkStorage();
//   }, [router, isRecognizing]);

//   const toggleDropdown = () => setDropdown(prev => !prev);

//   // Function to simulate storing an item in localStorage and triggering the notification
//   const handleReportClick = () => {
//     localStorage.removeItem("store"); // Remove notification from localStorage
//     setNotification(false); // Hide the notification dot
//   };

//   return (
//     <>
//       <Head>
//         <title>Shakktii Interview Trainer</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <div className="min-h-screen bg-gradient-to-b text-white px-4 bg-cover flex flex-col items-center justify-center" style={{ backgroundImage: "url('/bg.gif')" }}>
//         {/* Navigation Bar */}
//         <nav className="flex justify-between items-center py-4 px-6 bg-black bg-opacity-50 w-full">
//           <div className="text-white text-lg font-bold">Shaktti AI</div>
//           <ul className="flex space-x-6 text-sm">
//             <li className="hover:text-purple-400 cursor-pointer">Home</li>
//             <Link href={'/oldreport'}>
//               <li className="relative hover:text-purple-400 cursor-pointer" onClick={handleReportClick}>
//                 Reports
//                 {/* Show the notification red dot if true */}
//                 {notification && (
//                   <span className="absolute top-0 right-0 bg-red-500 text-white text-xs rounded-full w-2.5 h-2.5"></span>
//                 )}
//               </li>
//             </Link>
//             <div className="relative">
//               {/* User Dropdown */}
//               {user?.value && (
//                 <div className="relative">
//                   <MdAccountCircle
//                     className="text-2xl md:text-3xl mx-2 cursor-pointer"
//                     onClick={toggleDropdown} // Toggle on click
//                   />
//                   {dropdown && (
//                     <div className="absolute right-0 shadow-xl top-10 rounded-md w-40 border-2 border-solid border-gray-300">
//                       <ul>
//                         {/* Profile Link */}
//                         <Link href={'/profile'}><li className="hover:text-blue-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100">
//                           Profile
//                         </li></Link>
//                         {/* Logout Link */}
//                         <li
//                           onClick={Logout}
//                           className="hover:text-red-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100"
//                         >
//                           Logout
//                         </li>
//                       </ul>
//                     </div>
//                   )}
//                 </div>
//               )}

//               {/* Login button for guests */}
//               {!user?.value && (
//                 <Link href="/login">
//                   <div className="ml-4">
//                     <button className="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-opacity-50 transition ease-in-out duration-200">
//                       Login
//                     </button>
//                   </div>
//                 </Link>
//               )}
//             </div>
//           </ul>
//         </nav>

//         {/* Header Section */}
//         <div className="flex flex-col items-center text-center">
//           {/* Logo */}
//           <div className="w-20 h-20 mt-5 border-2 border-white rounded-full flex items-center justify-center">
//             <img src="/Logo.png" alt="Logo" className="w-16 h-16 object-contain" />
//           </div>

//           <h1 className="text-4xl font-bold mt-4 text-pink-400">Job</h1>
//           <h2 className="text-3xl font-bold text-pink-500">Interview</h2>

//           {/* Image Section */}
//           <div className="flex justify-center mt-4 mb-4">
//             <img
//               src="/home.png"
//               alt="Job Interview"
//               className="max-w-sm w-full h-auto object-contain"
//             />
//           </div>

//           {/* Description */}
//           <p className="text-center text-gray-300 max-w-lg mx-auto">
//             Landing your dream job starts with a great interview. We provide expert tips, real-world
//             insights, and proven strategies to help you impress employers and stand out from the
//             competition.
//           </p>

//           {/* List of Services */}
//           <ul className="mt-4 text-center space-y-2 text-gray-200">
//             <li>✅ <span className="text-pink-400">Interview Preparation</span> - Master common questions.</li>
//             <li>✅ <span className="text-pink-400">Resume & Cover Letter Tips</span> - Showcase your skills.</li>
//             <li>✅ <span className="text-pink-400">Career Coaching</span> - Get expert guidance.</li>
//           </ul>

//           {/* Informational text about speech recognition */}
//           <div className="mt-6 flex justify-center pb-10">
//             <p className="text-lg font-semibold text-gray-200">
//               Please speak the phrase <span className="text-pink-500">"I am ready"</span> to proceed.
//             </p>
//           </div>
//           Speak OR Click On Get Started
//           <div className="mt-6 flex justify-center pb-10">
//             <Link href={'/role'}>
//               <button className="bg-pink-500 text-white py-3 px-6 rounded-lg text-lg font-semibold hover:bg-pink-600">
//                 GET STARTED
//               </button>
//             </Link>
//           </div>
//         </div>
//       </div>
//     </>
//   );
// }



// //perfect
// import { useState, useEffect, useRef } from "react";
// import Link from "next/link";
// import Head from "next/head";
// import { IoIosArrowBack } from "react-icons/io";
// import { MdAccountCircle } from 'react-icons/md';
// import { useRouter } from 'next/router'; // For programmatic navigation



// export default function Home({ Logout, user }) {
//   const [dropdown, setDropdown] = useState(false);
//   const [notification, setNotification] = useState(false); // State to track the notification
//   const router = useRouter(); // Next.js router to navigate to /role
//   const recognition = useRef(null); // Reference to the speech recognition instance
//   const [isRecognizing, setIsRecognizing] = useState(false); // To track whether recognition is ongoing
// const[userr, setUserr] = useState(null);

//   const speak = (text) => {
//     const utterance = new SpeechSynthesisUtterance(text);
//     utterance.lang = 'en-US'; // Set language to English


//     window.speechSynthesis.speak(utterance);
//   };



// // console.log("this is User",user);


// useEffect(() => {
//   const userFromStorage = JSON.parse(localStorage.getItem('user'));

//   // console.log(userFromStorage);
//   setUserr(userFromStorage);

//   // No need to speak until the user is set
//   if (userFromStorage) {
//     // Speak the instructions once user data is loaded
//     const firstName = userFromStorage?.fullName?.split(' ')[0];
//     speak(`Hey ${firstName}, welcome back! Just say 'I'm ready' when you're all set!`);
//   }
// }, []); // Only runs once when the component is mounted


//   useEffect(() => {
//     // Initialize Speech Recognition API

//     const initSpeechRecognition = () => {
//       if (window.SpeechRecognition || window.webkitSpeechRecognition) {
//         recognition.current = new (window.SpeechRecognition || window.webkitSpeechRecognition)();
//         recognition.current.lang = "en-US";
//         recognition.current.continuous = true; // Continuous recognition
//         recognition.current.interimResults = false;

//         recognition.current.onstart = () => {
//           console.log("Speech recognition started.");
//           setIsRecognizing(true); // Set the recognizing flag to true
//         };

//         recognition.current.onend = () => {
//           console.log("Speech recognition ended.");
//           setIsRecognizing(false); // Set the recognizing flag to false

//           // Restart recognition only if it's fully ended and not already recognizing
//           if (recognition.current && !isRecognizing && recognition.current.state === "inactive") {
//             console.log("Speech recognition restarted."); // Debug log
//             recognition.current.start(); // Restart recognition
//           }
//         };

//         recognition.current.onresult = (event) => {
//           const transcript = event.results[0][0].transcript.toLowerCase();
//           console.log("Transcript: ", transcript);

//           // If the user says "I am ready", navigate to /role
//           if (transcript.includes("i am ready")) {
//             router.push("/role"); // Redirect to /role when "I am ready" is spoken
//           }
//         };

//         // Start listening when the page loads if it's not already started
//         if (recognition.current && !isRecognizing) {
//           recognition.current.start();
//         }
//       } else {
//         console.error("Speech recognition is not supported in this browser.");
//       }
//     };

//     initSpeechRecognition();

//     // Check if there’s a notification stored in localStorage when the component mounts
//     const checkStorage = () => {
//       const storedNotification = localStorage.getItem("store");
//       if (storedNotification) {
//         setNotification(true);
//       }
//     };

//     checkStorage();
//   }, [router, isRecognizing]);

//   const toggleDropdown = () => setDropdown(prev => !prev);

//   // Function to simulate storing an item in localStorage and triggering the notification
//   const handleReportClick = () => {
//     localStorage.removeItem("store"); // Remove notification from localStorage
//     setNotification(false); // Hide the notification dot
//   };

//   return (
//     <>
//       <Head>
//         <title>Shakktii Interview Trainer</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <div className="min-h-screen bg-gradient-to-b text-white px-4 bg-cover flex flex-col items-center justify-center" style={{ backgroundImage: "url('/bg.gif')" }}>
//         {/* Navigation Bar */}
//         <nav className="flex justify-between items-center py-4 px-6 bg-black bg-opacity-50 w-full">
//           <div className="text-white text-lg font-bold">Shaktti AI</div>
//           <ul className="flex space-x-6 text-sm">
//             <li className="hover:text-purple-400 cursor-pointer">Home</li>
//             <Link href={'/oldreport'}>
//               <li className="relative hover:text-purple-400 cursor-pointer" onClick={handleReportClick}>
//                 Reports
//                 {/* Show the notification red dot if true */}
//                 {notification && (
//                   <span className="absolute top-0 right-0 bg-red-500 text-white text-xs rounded-full w-2.5 h-2.5"></span>
//                 )}
//               </li>
//             </Link>
//             <div className="relative">
//               {/* User Dropdown */}
//               {user?.value && (
//                 <div className="relative">
//                   <MdAccountCircle
//                     className="text-2xl md:text-3xl mx-2 cursor-pointer"
//                     onClick={toggleDropdown} // Toggle on click
//                   />
//                   {dropdown && (
//                     <div className="absolute right-0 shadow-xl top-10 rounded-md w-40 border-2 border-solid border-gray-300">
//                       <ul>
//                         {/* Profile Link */}
//                         <Link href={'/profile'}><li className="hover:text-blue-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100">
//                           Profile
//                         </li></Link>
//                         {/* Logout Link */}
//                         <li
//                           onClick={Logout}
//                           className="hover:text-red-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100"
//                         >
//                           Logout
//                         </li>
//                       </ul>
//                     </div>
//                   )}
//                 </div>
//               )}

//               {/* Login button for guests */}
//               {!user?.value && (
//                 <Link href="/login">
//                   <div className="ml-4">
//                     <button className="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-opacity-50 transition ease-in-out duration-200">
//                       Login
//                     </button>
//                   </div>
//                 </Link>
//               )}
//             </div>
//           </ul>
//         </nav>

//         {/* Header Section */}
//         <div className="flex flex-col items-center text-center">
//           {/* Logo */}
//           <div className="w-20 h-20 mt-5 border-2 border-white rounded-full flex items-center justify-center">
//             <img src="/Logo.png" alt="Logo" className="w-16 h-16 object-contain" />
//           </div>

//           <h1 className="text-4xl font-bold mt-4 text-pink-400">Job</h1>
//           <h2 className="text-3xl font-bold text-pink-500">Interview</h2>

//           {/* Image Section */}
//           <div className="flex justify-center mt-4 mb-4">
//             <img
//               src="/home.png"
//               alt="Job Interview"
//               className="max-w-sm w-full h-auto object-contain"
//             />
//           </div>

//           {/* Description */}
//           <p className="text-center text-gray-300 max-w-lg mx-auto">
//             Landing your dream job starts with a great interview. We provide expert tips, real-world
//             insights, and proven strategies to help you impress employers and stand out from the
//             competition.
//           </p>

//           {/* List of Services */}
//           <ul className="mt-4 text-center space-y-2 text-gray-200">
//             <li>✅ <span className="text-pink-400">Interview Preparation</span> - Master common questions.</li>
//             <li>✅ <span className="text-pink-400">Resume & Cover Letter Tips</span> - Showcase your skills.</li>
//             <li>✅ <span className="text-pink-400">Career Coaching</span> - Get expert guidance.</li>
//           </ul>

//           {/* Informational text about speech recognition */}
//           <div className="mt-6 flex justify-center pb-10">
//             <p className="text-lg font-semibold text-gray-200">
//               Please speak the phrase <span className="text-pink-500">"I am ready"</span> to proceed.
//             </p>
//           </div>
//           Speak OR Click On Get Started
//           <div className="mt-6 flex justify-center pb-10">
//             <Link href={'/role'}>
//               <button className="bg-pink-500 text-white py-3 px-6 rounded-lg text-lg font-semibold hover:bg-pink-600">
//                 GET STARTED
//               </button>
//             </Link>
//           </div>

//         </div>
//       </div>
//     </>
//   );
// }



// import { useState, useEffect, useRef } from "react";
// import OwlModel from '../components/OwlModel'
// import Link from "next/link";
// import Head from "next/head";
// import { IoIosArrowBack } from "react-icons/io";
// import { MdAccountCircle } from 'react-icons/md';
// import { useRouter } from 'next/router'; // For programmatic navigation

// export default function Home({ Logout, user }) {
//   const [dropdown, setDropdown] = useState(false);
//   const [notification, setNotification] = useState(false); // State to track the notification
//   const router = useRouter(); // Next.js router to navigate to /role
//   const recognition = useRef(null); // Reference to the speech recognition instance
//   const [isRecognizing, setIsRecognizing] = useState(false); // To track whether recognition is ongoing

//   const speak = (text) => {
//     const utterance = new SpeechSynthesisUtterance(text);
//     utterance.lang = 'en-US'; // Set language to English
//     window.speechSynthesis.speak(utterance);
//   };

//   useEffect(() => {
//     // Delay speech synthesis for 1 second after page load
//     const timeoutId = setTimeout(() => {
//       // Check if the device is iOS and adjust the speech message accordingly
//       if (/iPhone|iPad|iPod/i.test(navigator.userAgent)) {
//         speak('Hi, I am Shakti, your interview trainer! Tap the screen to continue.');
//       } else {
//         speak('Hi, I am Shakti, your interview trainer! When you are ready, then speak the phrase "I am ready."');
//       }
//     }, 5000); // Delay by 1 second after page load

//     return () => clearTimeout(timeoutId); // Cleanup timeout on component unmount
//   }, []);

//   useEffect(() => {
//     // Initialize Speech Recognition API
//     const initSpeechRecognition = () => {
//       if (window.SpeechRecognition || window.webkitSpeechRecognition) {
//         recognition.current = new (window.SpeechRecognition || window.webkitSpeechRecognition)();
//         recognition.current.lang = "en-US";
//         recognition.current.continuous = true; // Continuous recognition
//         recognition.current.interimResults = false;

//         recognition.current.onstart = () => {
//           console.log("Speech recognition started.");
//           setIsRecognizing(true); // Set the recognizing flag to true
//         };

//         recognition.current.onend = () => {
//           console.log("Speech recognition ended.");
//           setIsRecognizing(false); // Set the recognizing flag to false

//           // Restart recognition only if it's fully ended and not already recognizing
//           if (recognition.current && !isRecognizing && recognition.current.state === "inactive") {
//             console.log("Speech recognition restarted."); // Debug log
//             recognition.current.start(); // Restart recognition
//           }
//         };

//         recognition.current.onresult = (event) => {
//           const transcript = event.results[0][0].transcript.toLowerCase();
//           console.log("Transcript: ", transcript);

//           // If the user says "I am ready", navigate to /role
//           if (transcript.includes("i am ready")) {
//             router.push("/role"); // Redirect to /role when "I am ready" is spoken
//           }
//         };

//         // Start listening when the page loads if it's not already started
//         if (recognition.current && !isRecognizing) {
//           recognition.current.start();
//         }
//       } else {
//         console.error("Speech recognition is not supported in this browser.");
//       }
//     };

//     initSpeechRecognition();

//     // Check if there’s a notification stored in localStorage when the component mounts
//     const checkStorage = () => {
//       const storedNotification = localStorage.getItem("store");
//       if (storedNotification) {
//         setNotification(true);
//       }
//     };

//     checkStorage();
//   }, [router, isRecognizing]);

//   const toggleDropdown = () => setDropdown(prev => !prev);

//   // Function to simulate storing an item in localStorage and triggering the notification
//   const handleReportClick = () => {
//     localStorage.removeItem("store"); // Remove notification from localStorage
//     setNotification(false); // Hide the notification dot
//   };

//   return (
//     <>
//       <Head>
//         <title>Shakktii Interview Trainer</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <div className="min-h-screen bg-gradient-to-b text-white px-4 bg-cover flex flex-col items-center justify-center" style={{ backgroundImage: "url('/bg.gif')" }}>
//         {/* Navigation Bar */}
//         <nav className="flex justify-between items-center py-4 px-6 bg-black bg-opacity-50 w-full">
//           <div className="text-white text-lg font-bold">Shaktti AI</div>
//           <ul className="flex space-x-6 text-sm">
//             <li className="hover:text-purple-400 cursor-pointer">Home</li>
//             <Link href={'/oldreport'}>
//               <li className="relative hover:text-purple-400 cursor-pointer" onClick={handleReportClick}>
//                 Reports
//                 {/* Show the notification red dot if true */}
//                 {notification && (
//                   <span className="absolute top-0 right-0 bg-red-500 text-white text-xs rounded-full w-2.5 h-2.5"></span>
//                 )}
//               </li>
//             </Link>
//             <div className="relative">
//               {/* User Dropdown */}
//               {user?.value && (
//                 <div className="relative">
//                   <MdAccountCircle
//                     className="text-2xl md:text-3xl mx-2 cursor-pointer"
//                     onClick={toggleDropdown} // Toggle on click
//                   />
//                   {dropdown && (
//                     <div className="absolute right-0 shadow-xl top-10 rounded-md w-40 border-2 border-solid border-gray-300">
//                       <ul>
//                         {/* Profile Link */}
//                         <Link href={'/profile'}><li className="hover:text-blue-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100">
//                           Profile
//                         </li></Link>
//                         {/* Logout Link */}
//                         <li
//                           onClick={Logout}
//                           className="hover:text-red-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100"
//                         >
//                           Logout
//                         </li>
//                       </ul>
//                     </div>
//                   )}
//                 </div>
//               )}

//               {/* Login button for guests */}
//               {!user?.value && (
//                 <Link href="/login">
//                   <div className="ml-4">
//                     <button className="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-opacity-50 transition ease-in-out duration-200">
//                       Login
//                     </button>
//                   </div>
//                 </Link>
//               )}
//             </div>
//           </ul>
//         </nav>

//         {/* Header Section */}
//         <div className="flex flex-col items-center text-center">
//           {/* Logo */}
//           <div style={{ height: '100vh' }}>
//       <OwlModel />
//     </div>
//           <div className="w-20 h-20 mt-5 border-2 border-white rounded-full flex items-center justify-center">
//             <img src="/Logo.png" alt="Logo" className="w-16 h-16 object-contain" />
//           </div>

//           <h1 className="text-4xl font-bold mt-4 text-pink-400">Job</h1>
//           <h2 className="text-3xl font-bold text-pink-500">Interview</h2>

//           {/* Image Section */}
//           <div className="flex justify-center mt-4 mb-4">
//             <img
//               src="/home.png"
//               alt="Job Interview"
//               className="max-w-sm w-full h-auto object-contain"
//             />
//           </div>

//           {/* Description */}
//           <p className="text-center text-gray-300 max-w-lg mx-auto">
//             Landing your dream job starts with a great interview. We provide expert tips, real-world
//             insights, and proven strategies to help you impress employers and stand out from the
//             competition.
//           </p>

//           {/* List of Services */}
//           <ul className="mt-4 text-center space-y-2 text-gray-200">
//             <li>✅ <span className="text-pink-400">Interview Preparation</span> - Master common questions.</li>
//             <li>✅ <span className="text-pink-400">Resume & Cover Letter Tips</span> - Showcase your skills.</li>
//             <li>✅ <span className="text-pink-400">Career Coaching</span> - Get expert guidance.</li>
//           </ul>

//           {/* Informational text about speech recognition */}
//           <div className="mt-6 flex justify-center pb-10">
//             <p className="text-lg font-semibold text-gray-200">
//               Please speak the phrase <span className="text-pink-500">"I am ready"</span> to proceed.
//             </p>
//           </div>
//           Speak OR Click On Get Started
//           <div className="mt-6 flex justify-center pb-10">
//             <Link href={'/role'}>
//               <button className="bg-pink-500 text-white py-3 px-6 rounded-lg text-lg font-semibold hover:bg-pink-600">
//                 GET STARTED
//               </button>
//             </Link>
//           </div>
//         </div>
//       </div>
//     </>
//   );
// }


// import { useState, useEffect, useRef } from "react";
// // import OwlModel from '../components/OwlModel'
// import Link from "next/link";
// import Head from "next/head";
// import { IoIosArrowBack } from "react-icons/io";
// import { MdAccountCircle } from 'react-icons/md';
// import { useRouter } from 'next/router'; // For programmatic navigation

// export default function Home({ Logout, user }) {
//   const [dropdown, setDropdown] = useState(false);
//   const [notification, setNotification] = useState(false); // State to track the notification
//   const router = useRouter(); // Next.js router to navigate to /role
//   const recognition = useRef(null); // Reference to the speech recognition instance
//   const [isRecognizing, setIsRecognizing] = useState(false); // To track whether recognition is ongoing
//   const [isIphone, setIsIphone] = useState(false); // State to track if the device is iPhone
// const[userr, setUserr] = useState(null);

//   const speak = (text) => {
//     const utterance = new SpeechSynthesisUtterance(text);
//     utterance.lang = 'en-US'; // Set language to English
//     window.speechSynthesis.speak(utterance);
//   };

//   useEffect(() => {
//     // Detect if the device is iPhone
//     if (/iPhone|iPad|iPod/i.test(navigator.userAgent)) {
//       setIsIphone(true);
//     }



//     // Delay speech synthesis for 1 second after page load
//     const timeoutId = setTimeout(() => {
//       // Check if the device is iOS and adjust the speech message accordingly
//       if (isIphone) {
//         const userFromStorage = JSON.parse(localStorage.getItem('user'));

//           // console.log(userFromStorage);
//           setUserr(userFromStorage);

//           // No need to speak until the user is set
//           if (userFromStorage) {
//             // Speak the instructions once user data is loaded
//             const firstName = userFromStorage?.fullName?.split(' ')[0];
//             speak(`Hey ${firstName}, welcome back! Just say 'I'm ready' when you're all set!`);
//           }
//       } else {
//         const userFromStorage = JSON.parse(localStorage.getItem('user'));

//           // console.log(userFromStorage);
//           setUserr(userFromStorage);

//           // No need to speak until the user is set
//           if (userFromStorage) {
//             // Speak the instructions once user data is loaded
//             const firstName = userFromStorage?.fullName?.split(' ')[0];
//             speak(`Hey ${firstName}, welcome back! Just say 'I'm ready' when you're all set!`);
//           } }
//     }, 1000); // Delay by 1 second after page load

//     return () => clearTimeout(timeoutId); // Cleanup timeout on component unmount
//   }, [isIphone]);

//   useEffect(() => {
//     // Initialize Speech Recognition API
//     const initSpeechRecognition = () => {
//       if (window.SpeechRecognition || window.webkitSpeechRecognition) {
//         recognition.current = new (window.SpeechRecognition || window.webkitSpeechRecognition)();
//         recognition.current.lang = "en-US";
//         recognition.current.continuous = true; // Continuous recognition
//         recognition.current.interimResults = false;

//         recognition.current.onstart = () => {
//           console.log("Speech recognition started.");
//           setIsRecognizing(true); // Set the recognizing flag to true
//         };

//         recognition.current.onend = () => {
//           console.log("Speech recognition ended.");
//           setIsRecognizing(false); // Set the recognizing flag to false

//           // Restart recognition only if it's fully ended and not already recognizing
//           if (recognition.current && !isRecognizing && recognition.current.state === "inactive") {
//             console.log("Speech recognition restarted."); // Debug log
//             recognition.current.start(); // Restart recognition
//           }
//         };

//         recognition.current.onresult = (event) => {
//           const transcript = event.results[0][0].transcript.toLowerCase();
//           console.log("Transcript: ", transcript);

//           // If the user says "I am ready", navigate to /role
//           if (transcript.includes("i am ready")) {
//             router.push("/role"); // Redirect to /role when "I am ready" is spoken
//           }
//         };

//         // Start listening when the page loads if it's not already started
//         if (recognition.current && !isRecognizing) {
//           recognition.current.start();
//         }
//       } else {
//         console.error("Speech recognition is not supported in this browser.");
//       }
//     };

//     initSpeechRecognition();

//     // Check if there’s a notification stored in localStorage when the component mounts
//     const checkStorage = () => {
//       const storedNotification = localStorage.getItem("store");
//       if (storedNotification) {
//         setNotification(true);
//       }
//     };

//     checkStorage();
//   }, [router, isRecognizing]);

//   const toggleDropdown = () => setDropdown(prev => !prev);

//   // Function to simulate storing an item in localStorage and triggering the notification
//   const handleReportClick = () => {
//     localStorage.removeItem("store"); // Remove notification from localStorage
//     setNotification(false); // Hide the notification dot
//   };

//   return (
//     <>
//       <Head>
//         <title>Shakktii Interview Trainer</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <div className="min-h-screen bg-gradient-to-b text-white px-4 bg-cover flex flex-col items-center justify-center" style={{ backgroundImage: "url('/bg.gif')" }}>
//         {/* Navigation Bar */}
//         <nav className="flex justify-between items-center py-4 px-6 bg-black bg-opacity-50 w-full">
//           <div className="text-white text-lg font-bold">Shakkti AI</div>
//           <ul className="flex space-x-6 text-sm">
//             <li className="hover:text-purple-400 cursor-pointer">Home</li>
//             <Link href={'/oldreport'}>
//               <li className="relative hover:text-purple-400 cursor-pointer" onClick={handleReportClick}>
//                 Reports
//                 {notification && (
//                   <span className="absolute top-0 right-0 bg-red-500 text-white text-xs rounded-full w-2.5 h-2.5"></span>
//                 )}
//               </li>
//             </Link>
//             <div className="relative">
//               {user?.value && (
//                 <div className="relative">
//                   <MdAccountCircle className="text-2xl md:text-3xl mx-2 cursor-pointer" onClick={toggleDropdown} />
//                   {dropdown && (
//                     <div className="absolute right-0 shadow-xl top-10 rounded-md w-40 border-2 border-solid border-gray-300">
//                       <ul>
//                         <Link href={'/profile'}>
//                           <li className="hover:text-blue-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100">Profile</li>
//                         </Link>
//                         <li onClick={Logout} className="hover:text-red-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100">Logout</li>
//                       </ul>
//                     </div>
//                   )}
//                 </div>
//               )}
//               {!user?.value && (
//                 <Link href="/login">
//                   <div className="ml-4">
//                     <button className="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-opacity-50 transition ease-in-out duration-200">Login</button>
//                   </div>
//                 </Link>
//               )}
//             </div>
//           </ul>
//         </nav>

//         {/* Header Section */}
//         <div className="flex flex-col items-center text-center">
//           {/* <div style={{ height: '100vh' }}>
//             <OwlModel  />
//           </div> */}
//           <div  className="w-20 h-20 mt-5 border-2 border-white rounded-full flex items-center justify-center">
//             <img src="/Logo.png" alt="Logo" className="w-16 h-16 object-contain" />
//           </div>
//           {isIphone && (
//           <>
//           <div onClick={() => speak(`Hey ${firstName}, welcome back! Just say 'I'm ready' when you're all set!`)}>
//           <h1  className="text-4xl font-bold mt-4 text-pink-400">Job</h1>
//           <h2  className="text-3xl font-bold text-pink-500">Interview</h2>
//           </div> </>
//          )}
//           {!isIphone && (
//           <>
//           <h1 className="text-4xl font-bold mt-4 text-pink-400">Job</h1>
//           <h2 className="text-3xl font-bold text-pink-500">Interview</h2>
//           </>
//          )}
//           <div className="flex justify-center mt-4 mb-4">
//             <img src="/home.png" alt="Job Interview" className="max-w-sm w-full h-auto object-contain" />
//           </div>

//           <p   className="text-center text-gray-300 max-w-lg mx-auto">
//             Landing your dream job starts with a great interview. We provide expert tips, real-world insights, and proven strategies to help you impress employers and stand out from the competition.
//           </p>

//           <ul className="mt-4 text-center space-y-2 text-gray-200">
//             <li>✅ <span className="text-pink-400">Interview Preparation</span> - Master common questions.</li>
//             <li>✅ <span className="text-pink-400">Resume & Cover Letter Tips</span> - Showcase your skills.</li>
//             <li>✅ <span className="text-pink-400">Career Coaching</span> - Get expert guidance.</li>
//           </ul>

//           <div className="mt-6 flex justify-center pb-10">
//             <p className="text-lg font-semibold text-gray-200">
//               Please speak the phrase <span className="text-pink-500">"I am ready"</span> to proceed.
//             </p>
//           </div>

//           {/* Only show the button for iPhone users */}
//           {isIphone && (
//             <div className="mt-6 flex justify-center pb-10">
//               <button
//                 className="bg-pink-500 text-white py-3 px-6 rounded-lg text-lg font-semibold hover:bg-pink-600"

//               >
//                 TAP TO CONTINUE
//               </button>
//             </div>
//           )}

//           {/* GET STARTED button */}

//             <div className="mt-6 flex justify-center pb-10">
//               <Link href={'/role'}>
//                 <button className="bg-pink-500 text-white py-3 px-6 rounded-lg text-lg font-semibold hover:bg-pink-600">
//                   GET STARTED
//                 </button>
//               </Link>
//             </div>

//         </div>
//       </div>
//     </>
//   );
// }


import { useState, useEffect, useRef } from "react";
import Link from "next/link";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { motion } from 'framer-motion';

import WhyMock from "../components/landingPage/whyMock";
import ScoreSection from "../components/landingPage/scoreSection";
import Footer from "@/components/landingPage/Footer";
import ProductValue from "@/components/landingPage/productValue";
import RealCost from "@/components/landingPage/RealCost";
import PerformanceTrade from "@/components/landingPage/PerformanceTrade";
import DemoVideo from "@/components/landingPage/DemoVideo";
import WhyFail from "@/components/landingPage/WhyFail";
import Testimonials from "@/components/landingPage/Testimonials";
export default function Home() {
  const router = useRouter();
  const [isCheckingAuth, setIsCheckingAuth] = useState(true);

  useEffect(() => {
    const getValueFromStorage = (key) => {
      if (typeof window === "undefined") return null;

      const localValue = localStorage.getItem(key);
      if (localValue) return localValue;

      const cookieMatch = document.cookie.match(new RegExp(`(?:^|;\\s*)${key}=([^;]+)`));
      return cookieMatch ? decodeURIComponent(cookieMatch[1]) : null;
    };

    const token = getValueFromStorage("token");
    const userData = getValueFromStorage("user");

    if (token && userData) {
      router.replace("/dashboard");
      return;
    }

    setIsCheckingAuth(false);
  }, [router]);

  if (isCheckingAuth) {
    return null;
  }

  // Animation Variants
  const fadeInUp = {
    hidden: { opacity: 0, y: 20 },
    visible: { opacity: 1, y: 0, transition: { duration: 0.6 } }
  };

  const staggerContainer = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: { staggerChildren: 0.2 }
    }
  };

  return (
    <>
      <Head>
        <title>Shakktii Interview Trainer</title>
        <meta name="description" content="Empower your learning journey through skill analysis, real-time chats, and gamified challenges to prepare for mock interviews — with MockMingle" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

  

    <section className="relative flex items-center pt-[30px] md:pt-[40px] pb-[20px] md:pb-[30px] overflow-visible min-h-auto md:min-h-[90vh]">
      <motion.div 
        initial="hidden"
        animate="visible"
        variants={staggerContainer}
        className="w-full max-w-[1440px] mx-auto grid grid-cols-1 md:grid-cols-2 gap-[10px] md:gap-[40px] items-center overflow-visible"
      >
        {/* ─── LEFT COLUMN ─── */}
        <div className="max-w-[750px] overflow-visible px-4 sm:px-6 md:pl-[73px] md:px-0 text-center md:text-left">
          
          <motion.h1 variants={fadeInUp} className="m-0 mb-[20px] md:mb-[28px] p-0 overflow-visible">
            <span className="block font-manrope font-extrabold text-[30px] sm:text-[42px] md:text-[min(57px,3.8vw)] leading-[1.15] md:leading-[1.37] tracking-[0.01em] whitespace-normal md:whitespace-nowrap overflow-visible bg-[linear-gradient(180deg,#666666_0%,#6F24E8_100%)] bg-clip-text text-transparent max-w-full md:max-w-[617px]">
              Crack Every Interview
            </span>
            <span className="block font-manrope font-extrabold text-[30px] sm:text-[42px] md:text-[min(57px,3.8vw)] leading-[1.1] md:leading-[1.2] tracking-[0.01em] whitespace-normal md:whitespace-nowrap overflow-visible">
              <span className="bg-[linear-gradient(180deg,#666666_0%,#6F24E8_100%)] bg-clip-text text-transparent">With</span>{" "}
              <span className="text-[#FF7046]">Ai Coaching</span>
            </span>
          </motion.h1>

          <motion.p variants={fadeInUp} className="font-manrope font-medium text-[16px] sm:text-[18px] md:text-[20px] leading-[24px] md:leading-[27px] tracking-[0.04em] text-[#1E0A40] mb-[30px] md:mb-[40px] max-w-[598px] mx-auto md:mx-0">
            Practice real interview scenarios, get instant AI-powered feedback, and land your dream job with confidence.
          </motion.p>

          <motion.div variants={fadeInUp} className="flex gap-[16px] md:gap-[24px] flex-wrap justify-center md:justify-start">
            <Link href="/dashboard">
              <motion.button 
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.95 }}
                className="w-full sm:w-[299px] h-[49px] rounded-[24.5px] border border-white bg-[linear-gradient(90.01deg,#FF7046_0.01%,#B3B3EA_172.54%)] shadow-[4px_11px_10.4px_rgba(0,0,0,0.12)] font-manrope font-semibold text-[16px] md:text-[18px] leading-[25px] tracking-[0.04em] text-[#1E0A40] cursor-pointer px-4"
              >
                Start Free Mock Interview
              </motion.button>
            </Link>

            <Link href="#demo-section">
              <motion.button 
                whileHover={{ scale: 1.05, backgroundColor: "#f9f9f9" }}
                whileTap={{ scale: 0.95 }}
                className="w-full sm:w-[257px] h-[49px] rounded-[24.5px] border border-white bg-white shadow-[4px_11px_10.4px_rgba(0,0,0,0.12)] font-manrope font-semibold text-[16px] md:text-[18px] leading-[25px] tracking-[0.04em] text-[#1E0A40] cursor-pointer px-4"
              >
                Watch Demo
              </motion.button>
            </Link>
          </motion.div>
        </div>

        {/* ─── RIGHT COLUMN (Visuals) ─── */}
        <div className="relative flex justify-center items-center w-full overflow-x-hidden px-0 sm:px-2 md:px-4 mt-[20px] md:mt-0">
          <div className="relative shrink-0 w-[648px] h-[540px] scale-[0.34] xs:scale-[0.42] sm:scale-[0.55] md:scale-[0.75] lg:scale-100 origin-top -mb-[320px] sm:-mb-[220px] md:-mb-[80px] lg:mb-0">
            
            {/* Animated SVG Border Drawing Effect */}
            <svg style={{ position: 'absolute', top: 0, left: 0, width: '648px', height: '540px', overflow: 'visible', zIndex: 1, pointerEvents: 'none' }}>
              <motion.path 
                initial={{ pathLength: 0 }}
                animate={{ pathLength: 1 }}
                transition={{ duration: 2, ease: "easeInOut" }}
                d="M 97.99 68 L 542.24 68 Q 571.24 68 571.24 97 M 571.24 210 L 571.24 449.83 Q 571.24 478.83 542.24 478.83 L 97.99 478.83 Q 68.99 478.83 68.99 449.83 M 68.99 228 L 68.99 298 M 68.99 112 Q 68.99 68 97.99 68"
                fill="none" 
                stroke="#7024EB" 
                strokeWidth="2" 
              />
            </svg>

            {/* Hero Image with Floating Effect */}
            <motion.div
              animate={{ y: [0, -10, 0] }}
              transition={{ duration: 4, repeat: Infinity, ease: "easeInOut" }}
              style={{ position: 'absolute', left: '138px', top: '0px', width: '380px', height: '521px', borderRadius: '21px', overflow: 'hidden', zIndex: 20 }}
            >
              <img src="/student_logo.png" alt="AI Interview" style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
            </motion.div>

            {/* Animated Stats - Pop in effect */}
            {[
              { label: "95%", sub: "Success Rate", top: "130px", left: "0px" },
              { label: "2K+", sub: "Active Users", top: "308px", left: "10px" },
              { label: "1M+", sub: "Practice Sessions", top: "104px", left: "500px" }
            ].map((stat, i) => (
              <motion.div
                key={i}
                initial={{ scale: 0, opacity: 0 }}
                animate={{ scale: 1, opacity: 1 }}
                transition={{ delay: 0.8 + (i * 0.2), type: "spring", stiffness: 100 }}
                style={{ position: 'absolute', left: stat.left, top: stat.top, width: '145px', zIndex: 30 }}
              >
                <div style={{ fontFamily: 'Manrope', fontWeight: 700, fontSize: '48px', color: '#FF7046', textAlign: 'center' }}>{stat.label}</div>
                <div style={{ fontFamily: 'Manrope', fontSize: '13px', color: '#333', textAlign: 'center' }}>{stat.sub}</div>
              </motion.div>
            ))}

          </div>
        </div>
      </motion.div>
    </section>
      <ScoreSection />
      <PerformanceTrade />
      <WhyMock />
      <section id="demo-section">
        <DemoVideo />
      </section>

      <WhyFail />
      <RealCost />
      <ProductValue />
      <Testimonials/>
      <Footer />
    </>
  );
}